-- Alchemy (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


TurtleGuide:RegisterQuestShellPlusGuide("Alchemy (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Alchemy (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 228 crafts in total).",
		},
		{
			type = "NOTE",
			title = "Before you start",
			note = "Totals assume you follow the main route below without alternatives.",
		},
		{
			type = "TRAIN",
			title = "Apprentice / Journeyman Alchemy (1-140)",
			note = "Telina Shadehand (Alah'Thalas), Milla Fairancora (Darnassus), Ghak Healtouch (Loch Modan), Alchemist Mallory (Elwynn Forest)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Alchemy (150-225)",
			note = "Kylanna Windwhisper (Feralas), Ainethil (Darnassus), Sylvanna Forestmoon (Darnassus)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Alchemy (225-300)",
			note = "Kylanna Windwhisper (Feralas)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Apprentice / Journeyman Alchemy (1-140)",
			note = "Yox Rackgadg (Blackstone Island), Tammix Razzfire (Durotar), Whuut (Orgrimmar), Carolai Anise (Tirisfal Glades)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Alchemy (150-225)",
			note = "Rogvar (Swamp of Sorrows), Doctor Herbert Halsey (Undercity), Yelmak (Orgrimmar)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Alchemy (225-300)",
			note = "Rogvar (Swamp of Sorrows)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Learn Alchemy (Apprentice)",
			note = "Skill 1-50",
		},
		{
			type = "USE",
			title = "Craft 40x Minor Healing Potion",
			note = "Takes you from 1 to 63.",
			skill = { profession = "Alchemy", from = 1, to = 63 },
			craft = { item = "Minor Healing Potion", count = 40 },
			reagents = { { item = "Peacebloom", qty = 1 }, { item = "Silverleaf", qty = 1 }, { item = "Empty Vial", qty = 1 } },
			source = "Auto-learned",
			alternatives = { "Elixir of Minor Defense", "Elixir of Lion's Strength" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Alchemy (Cap 150)",
			note = "Skill 50",
		},
		{
			type = "USE",
			title = "Craft 17x Elixir of Minor Agility",
			note = "Takes you from 63 to 80.",
			skill = { profession = "Alchemy", from = 63, to = 80 },
			craft = { item = "Elixir of Minor Agility", count = 17 },
			reagents = { { item = "Swiftthistle", qty = 1 }, { item = "Silverleaf", qty = 1 }, { item = "Empty Vial", qty = 1 } },
			source = "Recipe: Elixir of Minor Agility",
			alternatives = { "Minor Healing Potion", "Lesser Healing Potion", "Swiftness Potion" },
		},
		{
			type = "USE",
			title = "Craft 13x Blackmouth Oil",
			note = "Takes you from 80 to 90.",
			skill = { profession = "Alchemy", from = 80, to = 90 },
			craft = { item = "Blackmouth Oil", count = 13 },
			reagents = { { item = "Oily Blackmouth", qty = 2 }, { item = "Empty Vial", qty = 1 } },
			source = "Trainer",
			alternatives = { "Elixir of Minor Agility", "Swiftness Potion", "Discolored Healing Potion" },
		},
		{
			type = "USE",
			title = "Craft 30x Elixir of Giant Growth",
			note = "Takes you from 90 to 130.",
			skill = { profession = "Alchemy", from = 90, to = 130 },
			craft = { item = "Elixir of Giant Growth", count = 30 },
			reagents = { { item = "Deviate Fish", qty = 1 }, { item = "Earthroot", qty = 1 }, { item = "Empty Vial", qty = 1 } },
			source = "Recipe: Elixir of Giant Growth",
			alternatives = { "Blackmouth Oil", "Lesser Healing Potion", "Swiftness Potion" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Alchemy (Cap 225)",
			note = "Skill 125",
		},
		{
			type = "USE",
			title = "Craft 20x Fire Oil",
			note = "Takes you from 130 to 160.",
			skill = { profession = "Alchemy", from = 130, to = 160 },
			craft = { item = "Fire Oil", count = 20 },
			reagents = { { item = "Firefin Snapper", qty = 2 }, { item = "Empty Vial", qty = 1 } },
			source = "Trainer",
			alternatives = { "Elixir of Giant Growth", "Swim Speed Potion", "Holy Protection Potion" },
		},
		{
			type = "USE",
			title = "Craft 15x Elixir of Ogre's Strength",
			note = "Takes you from 160 to 195.",
			skill = { profession = "Alchemy", from = 160, to = 195 },
			craft = { item = "Elixir of Ogre's Strength", count = 15 },
			reagents = { { item = "Earthroot", qty = 1 }, { item = "Kingsblood", qty = 1 }, { item = "Leaded Vial", qty = 1 } },
			source = "Recipe: Elixir of Ogre's Strength",
			alternatives = { "Fire Oil", "Swim Speed Potion", "Healing Potion", "Shadow Protection Potion" },
		},
		{
			type = "USE",
			title = "Craft 5x Mighty Troll's Blood Potion",
			note = "Takes you from 195 to 220.",
			skill = { profession = "Alchemy", from = 195, to = 220 },
			craft = { item = "Mighty Troll's Blood Potion", count = 5 },
			reagents = { { item = "Liferoot", qty = 1 }, { item = "Bruiseweed", qty = 1 }, { item = "Leaded Vial", qty = 1 } },
			source = "Recipe: Mighty Troll's Blood Potion",
			alternatives = { "Elixir of Ogre's Strength", "Elixir of Firepower", "Greater Healing Potion" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Alchemy (Cap 300)",
			note = "Skill 200",
		},
		{
			type = "USE",
			title = "Craft 13x Nature Protection Potion",
			note = "Takes you from 220 to 230.",
			skill = { profession = "Alchemy", from = 220, to = 230 },
			craft = { item = "Nature Protection Potion", count = 13 },
			reagents = { { item = "Liferoot", qty = 1 }, { item = "Stranglekelp", qty = 1 }, { item = "Leaded Vial", qty = 1 } },
			source = "Recipe: Nature Protection Potion",
			alternatives = { "Mighty Troll's Blood Potion", "Elixir of Greater Defense", "Elixir of Fortitude" },
		},
		{
			type = "USE",
			title = "Craft 7x Elixir of Greater Defense",
			note = "Takes you from 230 to 235.",
			skill = { profession = "Alchemy", from = 230, to = 235 },
			craft = { item = "Elixir of Greater Defense", count = 7 },
			reagents = { { item = "Wild Steelbloom", qty = 1 }, { item = "Goldthorn", qty = 1 }, { item = "Leaded Vial", qty = 1 } },
			source = "Trainer",
			alternatives = { "Nature Protection Potion", "Elixir of Fortitude", "Elixir of Agility" },
		},
		{
			type = "USE",
			title = "Craft 10x Elixir of Detect Undead",
			note = "Takes you from 235 to 250.",
			skill = { profession = "Alchemy", from = 235, to = 250 },
			craft = { item = "Elixir of Detect Undead", count = 10 },
			reagents = { { item = "Arthas' Tears", qty = 1 }, { item = "Crystal Vial", qty = 1 } },
			source = "Trainer",
			alternatives = { "Nature Protection Potion", "Elixir of Greater Defense", "Frost Protection Potion" },
		},
		{
			type = "USE",
			title = "Craft 7x Stonescale Oil",
			note = "Takes you from 250 to 255.",
			skill = { profession = "Alchemy", from = 250, to = 255 },
			craft = { item = "Stonescale Oil", count = 7 },
			reagents = { { item = "Stonescale Eel", qty = 1 }, { item = "Leaded Vial", qty = 1 } },
			source = "Trainer",
			alternatives = { "Elixir of Greater Defense", "Catseye Elixir", "Greater Mana Potion" },
		},
		{
			type = "USE",
			title = "Craft 13x Elixir of Detect Undead",
			note = "Takes you from 255 to 265.",
			skill = { profession = "Alchemy", from = 255, to = 265 },
			craft = { item = "Elixir of Detect Undead", count = 13 },
			reagents = { { item = "Arthas' Tears", qty = 1 }, { item = "Crystal Vial", qty = 1 } },
			source = "Trainer",
			alternatives = { "Stonescale Oil", "Elixir of Greater Agility", "Superior Healing Potion" },
		},
		{
			type = "USE",
			title = "Craft 13x Elixir of Greater Agility",
			note = "Takes you from 265 to 275.",
			skill = { profession = "Alchemy", from = 265, to = 275 },
			craft = { item = "Elixir of Greater Agility", count = 13 },
			reagents = { { item = "Sungrass", qty = 1 }, { item = "Goldthorn", qty = 1 }, { item = "Crystal Vial", qty = 1 } },
			source = "Trainer",
			alternatives = { "Elixir of Detect Undead", "Superior Healing Potion", "Elixir of Superior Defense" },
		},
		{
			type = "USE",
			title = "Craft 15x Greater Dreamless Sleep Potion",
			note = "Takes you from 275 to 290.",
			skill = { profession = "Alchemy", from = 275, to = 290 },
			craft = { item = "Greater Dreamless Sleep Potion", count = 15 },
			reagents = { { item = "Dreamfoil", qty = 2 }, { item = "Golden Sansam", qty = 1 }, { item = "Crystal Vial", qty = 1 } },
			source = "Recipe: Greater Dreamless Sleep",
			alternatives = { "Elixir of Greater Agility", "Elixir of Superior Defense", "Major Healing Potion" },
		},
		{
			type = "USE",
			title = "Craft 10x Greater Arcane Protection Potion",
			note = "Takes you from 290 to 300.",
			skill = { profession = "Alchemy", from = 290, to = 300 },
			craft = { item = "Greater Arcane Protection Potion", count = 10 },
			reagents = { { item = "Dream Dust", qty = 1 }, { item = "Dreamfoil", qty = 1 }, { item = "Crystal Vial", qty = 1 } },
			source = "Recipe: Greater Arcane Protection Potion",
			alternatives = { "Greater Dreamless Sleep Potion", "Elixir of Superior Defense", "Major Healing Potion" },
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Alchemy is maxed at 300.",
		},
	},
})
