-- Blacksmithing (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


TurtleGuide:RegisterQuestShellPlusGuide("Blacksmithing (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Blacksmithing (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 233 crafts in total).",
		},
		{
			type = "NOTE",
			title = "Before you start",
			note = "Totals assume you follow the main route below without alternatives.",
		},
		{
			type = "TRAIN",
			title = "Apprentice Blacksmithing (1-120)",
			note = "Smith Argus (Elwynn Forest), Delfrum Flintbeard (Darkshore), Groum Stonebeard (Ironforge), Dane Lindgren (Stormwind City)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Blacksmithing (15-150)",
			note = "Clarise Gnarltree (Duskwood), Rotgath Stonebeard (Ironforge), Therum Deepforge (Stormwind City), Smith Martin (Northwind)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Blacksmithing (200-300)",
			note = "Grumnus Steelshaper (Ironforge), Ironus Coldsteel (Ironforge), Borgus Steelhand (Stormwind City), Brikk Keencraft (Stranglethorn Vale)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Apprentice Blacksmithing (1-120)",
			note = "Thrag Stonehoof (Thunder Bluff), Ug'thok (Orgrimmar), Basil Frye (Undercity), Dwukk (Durotar)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Blacksmithing (15-150)",
			note = "Snarl (Orgrimmar), Traugh (The Barrens), Karn Stonehoof (Thunder Bluff), Thrag Stonehoof (Thunder Bluff)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Blacksmithing (125-275)",
			note = "Brikk Keencraft (Stranglethorn Vale), Ulf Stonetotem (Moonwhisper Coast), Saru Steelfury (Orgrimmar), James Van Brunt (Undercity)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Blacksmithing (200-300)",
			note = "Okothos Ironrager (Orgrimmar), Shayis Steelfury (Orgrimmar), Borgosh Corebender (Orgrimmar), Kelgruk Bloodaxe (Orgrimmar)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Learn Blacksmithing (Apprentice)",
			note = "Skill 1-50",
		},
		{
			type = "USE",
			title = "Craft 14x Rough Sharpening Stone",
			note = "Takes you from 1 to 35.",
			skill = { profession = "Blacksmithing", from = 1, to = 35 },
			craft = { item = "Rough Sharpening Stone", count = 14 },
			reagents = { { item = "Rough Stone", qty = 1 } },
			source = "Auto-learned",
			alternatives = { "Rough Weightstone", "Copper Bracers", "Rough Copper Vest" },
		},
		{
			type = "USE",
			title = "Craft 10x Rough Grinding Stone",
			note = "Takes you from 35 to 65.",
			skill = { profession = "Blacksmithing", from = 35, to = 65 },
			craft = { item = "Rough Grinding Stone", count = 10 },
			reagents = { { item = "Rough Stone", qty = 2 } },
			source = "Trainer",
			alternatives = { "Rough Sharpening Stone", "Rough Weightstone", "Copper Bracers", "Copper Chain Belt" },
		},
		{
			type = "USE",
			title = "Craft 11x Coarse Sharpening Stone",
			note = "Takes you from 65 to 73.",
			skill = { profession = "Blacksmithing", from = 65, to = 73 },
			craft = { item = "Coarse Sharpening Stone", count = 11 },
			reagents = { { item = "Coarse Stone", qty = 1 } },
			source = "Trainer",
			alternatives = { "Rough Grinding Stone", "Copper Chain Pants", "Coarse Weightstone", "Copper Chain Belt" },
		},
		{
			type = "USE",
			title = "Craft 2x Copper Chain Belt",
			note = "Takes you from 73 to 75.",
			skill = { profession = "Blacksmithing", from = 73, to = 75 },
			craft = { item = "Copper Chain Belt", count = 2 },
			reagents = { { item = "Copper Bar", qty = 6 } },
			source = "Trainer",
			alternatives = { "Rough Grinding Stone", "Coarse Sharpening Stone", "Coarse Weightstone" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Blacksmithing (Cap 150)",
			note = "Skill 50",
		},
		{
			type = "USE",
			title = "Craft 17x Coarse Grinding Stone",
			note = "Takes you from 75 to 88.",
			skill = { profession = "Blacksmithing", from = 75, to = 88 },
			craft = { item = "Coarse Grinding Stone", count = 17 },
			reagents = { { item = "Coarse Stone", qty = 2 } },
			source = "Trainer",
			alternatives = { "Rough Grinding Stone", "Coarse Sharpening Stone", "Copper Chain Pants" },
		},
		{
			type = "USE",
			title = "Craft 3x Copper Chain Belt",
			note = "Takes you from 88 to 90.",
			skill = { profession = "Blacksmithing", from = 88, to = 90 },
			craft = { item = "Copper Chain Belt", count = 3 },
			reagents = { { item = "Copper Bar", qty = 6 } },
			source = "Trainer",
			alternatives = { "Coarse Grinding Stone", "Copper Chain Pants", "Runed Copper Gauntlets" },
		},
		{
			type = "USE",
			title = "Craft 7x Runed Copper Gauntlets",
			note = "Takes you from 90 to 95.",
			skill = { profession = "Blacksmithing", from = 90, to = 95 },
			craft = { item = "Runed Copper Gauntlets", count = 7 },
			reagents = { { item = "Copper Bar", qty = 8 }, { item = "Rough Grinding Stone", qty = 2 } },
			source = "Trainer",
			alternatives = { "Coarse Grinding Stone", "Copper Chain Belt", "Runed Copper Belt" },
		},
		{
			type = "USE",
			title = "Craft 15x Runed Copper Belt",
			note = "Takes you from 95 to 125.",
			skill = { profession = "Blacksmithing", from = 95, to = 125 },
			craft = { item = "Runed Copper Belt", count = 15 },
			reagents = { { item = "Copper Bar", qty = 10 } },
			source = "Trainer",
			alternatives = { "Coarse Grinding Stone", "Copper Chain Belt", "Runed Copper Gauntlets" },
		},
		{
			type = "USE",
			title = "Craft 11x Heavy Sharpening Stone",
			note = "Takes you from 125 to 133.",
			skill = { profession = "Blacksmithing", from = 125, to = 133 },
			craft = { item = "Heavy Sharpening Stone", count = 11 },
			reagents = { { item = "Heavy Stone", qty = 1 } },
			source = "Trainer",
			alternatives = { "Heavy Weightstone", "Runed Copper Belt", "Heavy Grinding Stone" },
		},
		{
			type = "USE",
			title = "Craft 7x Heavy Grinding Stone",
			note = "Takes you from 133 to 138.",
			skill = { profession = "Blacksmithing", from = 133, to = 138 },
			craft = { item = "Heavy Grinding Stone", count = 7 },
			reagents = { { item = "Heavy Stone", qty = 3 } },
			source = "Trainer",
			alternatives = { "Heavy Sharpening Stone", "Heavy Weightstone", "Runed Copper Belt" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Blacksmithing (Cap 225)",
			note = "Skill 125",
		},
		{
			type = "USE",
			title = "Craft 2x Rough Bronze Bracers",
			note = "Takes you from 138 to 158.",
			skill = { profession = "Blacksmithing", from = 138, to = 158 },
			craft = { item = "Rough Bronze Bracers", count = 2 },
			reagents = { { item = "Bronze Bar", qty = 4 } },
			source = "Recipe: Plans: Rough Bronze Bracers",
			alternatives = { "Heavy Sharpening Stone", "Heavy Weightstone", "Heavy Grinding Stone" },
		},
		{
			type = "USE",
			title = "Craft 10x Patterned Bronze Bracers",
			note = "Takes you from 158 to 165.",
			skill = { profession = "Blacksmithing", from = 158, to = 165 },
			craft = { item = "Patterned Bronze Bracers", count = 10 },
			reagents = { { item = "Bronze Bar", qty = 5 }, { item = "Coarse Grinding Stone", qty = 2 } },
			source = "Trainer",
			alternatives = { "Rough Bronze Bracers", "Rough Bronze Leggings", "Lordaeron Breastplate" },
		},
		{
			type = "USE",
			title = "Craft 7x Lordaeron Breastplate",
			note = "Takes you from 165 to 170.",
			skill = { profession = "Blacksmithing", from = 165, to = 170 },
			craft = { item = "Lordaeron Breastplate", count = 7 },
			reagents = { { item = "Copper Bar", qty = 16 }, { item = "Tigerseye", qty = 2 }, { item = "Rough Grinding Stone", qty = 3 } },
			source = "Recipe: Plans: Lordaeron Breastplate",
			alternatives = { "Rough Bronze Bracers", "Patterned Bronze Bracers", "Silvered Bronze Boots" },
		},
		{
			type = "USE",
			title = "Craft 7x Silvered Bronze Boots",
			note = "Takes you from 170 to 175.",
			skill = { profession = "Blacksmithing", from = 170, to = 175 },
			craft = { item = "Silvered Bronze Boots", count = 7 },
			reagents = { { item = "Bronze Bar", qty = 6 }, { item = "Silver Bar", qty = 1 }, { item = "Coarse Grinding Stone", qty = 2 } },
			source = "Trainer",
			alternatives = { "Patterned Bronze Bracers", "Rough Bronze Leggings", "Silvered Bronze Gauntlets" },
		},
		{
			type = "USE",
			title = "Craft 7x Silvered Bronze Gauntlets",
			note = "Takes you from 175 to 180.",
			skill = { profession = "Blacksmithing", from = 175, to = 180 },
			craft = { item = "Silvered Bronze Gauntlets", count = 7 },
			reagents = { { item = "Bronze Bar", qty = 8 }, { item = "Silver Bar", qty = 1 }, { item = "Coarse Grinding Stone", qty = 2 } },
			source = "Trainer",
			alternatives = { "Patterned Bronze Bracers", "Silvered Bronze Boots", "Silvered Bronze Leggings" },
		},
		{
			type = "USE",
			title = "Craft 7x Silvered Bronze Leggings",
			note = "Takes you from 180 to 185.",
			skill = { profession = "Blacksmithing", from = 180, to = 185 },
			craft = { item = "Silvered Bronze Leggings", count = 7 },
			reagents = { { item = "Bronze Bar", qty = 12 }, { item = "Silver Bar", qty = 4 }, { item = "Coarse Grinding Stone", qty = 2 } },
			source = "Recipe: Plans: Silvered Bronze Leggings",
			alternatives = { "Silvered Bronze Boots", "Silvered Bronze Gauntlets", "Ironforge Gauntlets" },
		},
		{
			type = "USE",
			title = "Craft 15x Golden Scale Bracers",
			note = "Takes you from 185 to 200.",
			skill = { profession = "Blacksmithing", from = 185, to = 200 },
			craft = { item = "Golden Scale Bracers", count = 15 },
			reagents = { { item = "Steel Bar", qty = 5 }, { item = "Heavy Grinding Stone", qty = 2 } },
			source = "Trainer",
			alternatives = { "Silvered Bronze Boots", "Silvered Bronze Leggings", "Green Iron Bracers" },
		},
		{
			type = "USE",
			title = "Craft 7x Solid Sharpening Stone",
			note = "Takes you from 200 to 205.",
			skill = { profession = "Blacksmithing", from = 200, to = 205 },
			craft = { item = "Solid Sharpening Stone", count = 7 },
			reagents = { { item = "Solid Stone", qty = 1 } },
			source = "Trainer",
			alternatives = { "Solid Weightstone", "Solid Grinding Stone", "Golden Scale Bracers" },
		},
		{
			type = "USE",
			title = "Craft 5x Golden Scale Bracers",
			note = "Takes you from 205 to 223.",
			skill = { profession = "Blacksmithing", from = 205, to = 223 },
			craft = { item = "Golden Scale Bracers", count = 5 },
			reagents = { { item = "Steel Bar", qty = 5 }, { item = "Heavy Grinding Stone", qty = 2 } },
			source = "Trainer",
			alternatives = { "Solid Sharpening Stone", "Solid Grinding Stone", "Green Iron Bracers" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Blacksmithing (Cap 300)",
			note = "Skill 200",
		},
		{
			type = "USE",
			title = "Craft 12x Steel Plate Helm",
			note = "Takes you from 223 to 245.",
			skill = { profession = "Blacksmithing", from = 223, to = 245 },
			craft = { item = "Steel Plate Helm", count = 12 },
			reagents = { { item = "Steel Bar", qty = 14 }, { item = "Solid Grinding Stone", qty = 1 } },
			source = "Trainer",
			alternatives = { "Golden Scale Bracers", "Steel Plate Boots", "Steel Weapon Chain" },
		},
		{
			type = "USE",
			title = "Craft 5x Mithril Spurs",
			note = "Takes you from 245 to 250.",
			skill = { profession = "Blacksmithing", from = 245, to = 250 },
			craft = { item = "Mithril Spurs", count = 5 },
			reagents = { { item = "Mithril Bar", qty = 4 }, { item = "Solid Grinding Stone", qty = 3 } },
			source = "Recipe: Plans: Mithril Spurs",
			alternatives = { "Steel Plate Helm", "Steel Breastplate", "Steel Plate Pauldrons" },
		},
		{
			type = "USE",
			title = "Craft 5x Dense Sharpening Stone",
			note = "Takes you from 250 to 258.",
			skill = { profession = "Blacksmithing", from = 250, to = 258 },
			craft = { item = "Dense Sharpening Stone", count = 5 },
			reagents = { { item = "Dense Stone", qty = 1 } },
			source = "Trainer",
			alternatives = { "Dense Weightstone", "Dense Grinding Stone", "Mithril Spurs" },
		},
		{
			type = "USE",
			title = "Craft 10x Mithril Spurs",
			note = "Takes you from 258 to 265.",
			skill = { profession = "Blacksmithing", from = 258, to = 265 },
			craft = { item = "Mithril Spurs", count = 10 },
			reagents = { { item = "Mithril Bar", qty = 4 }, { item = "Solid Grinding Stone", qty = 3 } },
			source = "Recipe: Plans: Mithril Spurs",
			alternatives = { "Dense Sharpening Stone", "Dense Weightstone", "Mithril Scale Gloves" },
		},
		{
			type = "USE",
			title = "Craft 10x Radiant Belt",
			note = "Takes you from 265 to 275.",
			skill = { profession = "Blacksmithing", from = 265, to = 275 },
			craft = { item = "Radiant Belt", count = 10 },
			reagents = { { item = "Thorium Bar", qty = 10 }, { item = "Heart of Fire", qty = 2 } },
			source = "Recipe: Plans: Radiant Belt",
			alternatives = { "Mithril Spurs", "Orcish War Leggings", "Heavy Mithril Breastplate" },
		},
		{
			type = "USE",
			title = "Craft 7x Dark Iron Belt Buckle",
			note = "Takes you from 275 to 280.",
			skill = { profession = "Blacksmithing", from = 275, to = 280 },
			craft = { item = "Dark Iron Belt Buckle", count = 7 },
			reagents = { { item = "Dark Iron Bar", qty = 2 }, { item = "Iron Buckle", qty = 1 }, { item = "Essence of Fire", qty = 1 }, { item = "Dense Grinding Stone", qty = 2 } },
			source = "Recipe: Plans: Dark Iron Belt Buckle",
			alternatives = { "Thorium Shield Spike", "Dark Iron Mail", "Radiant Belt" },
		},
		{
			type = "USE",
			title = "Craft 20x Dark Iron Shoulders",
			note = "Takes you from 280 to 300.",
			skill = { profession = "Blacksmithing", from = 280, to = 300 },
			craft = { item = "Dark Iron Shoulders", count = 20 },
			reagents = { { item = "Dark Iron Bar", qty = 6 }, { item = "Heart of Fire", qty = 1 } },
			source = "Recipe: Plans: Dark Iron Shoulders",
			alternatives = { "Dark Iron Belt Buckle", "Thorium Bracers", "Radiant Boots" },
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Blacksmithing is maxed at 300.",
		},
	},
})
