-- Cooking (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


TurtleGuide:RegisterQuestShellPlusGuide("Cooking (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Cooking (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 185 crafts in total).",
		},
		{
			type = "NOTE",
			title = "Before you start",
			note = "Totals assume you follow the main route below without alternatives.",
		},
		{
			type = "TRAIN",
			title = "Apprentice Cooking (1-125)",
			note = "Cook Ghilm (Dun Morogh), Gremlock Pilsnor (Dun Morogh), Tomas (Elwynn Forest), Verrus Trueshine (Alah'Thalas)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Cooking (50-150)",
			note = "Verrus Trueshine (Alah'Thalas), Cook Ghilm (Dun Morogh), Gremlock Pilsnor (Dun Morogh), Tomas (Elwynn Forest)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Cooking (125-225)",
			note = "Henry Stern (Razorfen Downs), Cook Ghilm (Dun Morogh), Gremlock Pilsnor (Dun Morogh), Tomas (Elwynn Forest)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Cooking (200-300)",
			note = "Henry Stern (Razorfen Downs), Cook Ghilm (Dun Morogh), Gremlock Pilsnor (Dun Morogh), Tomas (Elwynn Forest)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Apprentice Cooking (1-125)",
			note = "Cook Torka (Durotar), Pyall Silentstride (Mulgore), Duhng (The Barrens), Shazzlan (Blackstone Island)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Cooking (50-150)",
			note = "Cook Torka (Durotar), Pyall Silentstride (Mulgore), Duhng (The Barrens), Shazzlan (Blackstone Island)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Cooking (125-225)",
			note = "Henry Stern (Razorfen Downs), Cook Torka (Durotar), Pyall Silentstride (Mulgore), Duhng (The Barrens)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Cooking (200-300)",
			note = "Henry Stern (Razorfen Downs), Cook Torka (Durotar), Pyall Silentstride (Mulgore), Duhng (The Barrens)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Learn Cooking (Apprentice)",
			note = "Skill 1-50",
		},
		{
			type = "USE",
			title = "Craft 40x Brilliant Smallfish",
			note = "Takes you from 1 to 58.",
			skill = { profession = "Cooking", from = 1, to = 58 },
			craft = { item = "Brilliant Smallfish", count = 40 },
			reagents = { { item = "Raw Brilliant Smallfish", qty = 1 } },
			source = "Recipe: Brilliant Smallfish",
			alternatives = { "Slitherskin Mackerel", "Roasted Boar Meat", "Charred Wolf Meat", "Herb Baked Egg", "Crispy Bat Wing", "Gingerbread Cookie" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Cooking (Cap 150)",
			note = "Skill 50",
		},
		{
			type = "USE",
			title = "Craft 32x Longjaw Mud Snapper",
			note = "Takes you from 58 to 105.",
			skill = { profession = "Cooking", from = 58, to = 105 },
			craft = { item = "Longjaw Mud Snapper", count = 32 },
			reagents = { { item = "Raw Longjaw Mud Snapper", qty = 1 } },
			source = "Recipe: Longjaw Mud Snapper",
			alternatives = { "Brilliant Smallfish", "Slitherskin Mackerel", "Rainbow Fin Albacore", "Loch Frenzy Delight", "Kaldorei Spider Kabob", "Roasted Boar Meat" },
		},
		{
			type = "USE",
			title = "Craft 25x Dig Rat Stew",
			note = "Takes you from 105 to 145.",
			skill = { profession = "Cooking", from = 105, to = 145 },
			craft = { item = "Dig Rat Stew", count = 25 },
			reagents = { { item = "Dig Rat", qty = 1 } },
			source = "Recipe: Dig Rat Stew",
			alternatives = { "Longjaw Mud Snapper", "Bristle Whisker Catfish", "Rainbow Fin Albacore", "Loch Frenzy Delight", "Savory Deviate Delight", "Coyote Steak" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Cooking (Cap 225)",
			note = "Skill 125",
		},
		{
			type = "USE",
			title = "Craft 13x Bristle Whisker Catfish",
			note = "Takes you from 145 to 155.",
			skill = { profession = "Cooking", from = 145, to = 155 },
			craft = { item = "Bristle Whisker Catfish", count = 13 },
			reagents = { { item = "Raw Bristle Whisker Catfish", qty = 1 } },
			source = "Recipe: Bristle Whisker Catfish",
			alternatives = { "Dig Rat Stew", "Savory Deviate Delight", "Cooked Crab Claw", "Dry Pork Ribs", "Crocolisk Steak", "Clam Chowder" },
		},
		{
			type = "USE",
			title = "Craft 10x Lean Wolf Steak",
			note = "Takes you from 155 to 175.",
			skill = { profession = "Cooking", from = 155, to = 175 },
			craft = { item = "Lean Wolf Steak", count = 10 },
			reagents = { { item = "Lean Wolf Flank", qty = 1 }, { item = "Mild Spices", qty = 1 } },
			source = "Recipe: Lean Wolf Steak",
			alternatives = { "Dig Rat Stew", "Bristle Whisker Catfish", "Clam Chowder", "Goblin Deviled Clams", "Gooey Spider Cake", "Lean Venison" },
		},
		{
			type = "USE",
			title = "Craft 15x Rockscale Cod",
			note = "Takes you from 175 to 210.",
			skill = { profession = "Cooking", from = 175, to = 210 },
			craft = { item = "Rockscale Cod", count = 15 },
			reagents = { { item = "Raw Rockscale Cod", qty = 1 } },
			source = "Recipe: Rockscale Cod",
			alternatives = { "Mithril Head Trout", "Lean Wolf Steak", "Goblin Deviled Clams", "Gooey Spider Cake", "Lean Venison", "Crocolisk Gumbo" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Cooking (Cap 300)",
			note = "Skill 200",
		},
		{
			type = "USE",
			title = "Craft 5x Mithril Head Trout",
			note = "Takes you from 210 to 230.",
			skill = { profession = "Cooking", from = 210, to = 230 },
			craft = { item = "Mithril Head Trout", count = 5 },
			reagents = { { item = "Raw Mithril Head Trout", qty = 1 } },
			source = "Recipe: Mithril Head Trout",
			alternatives = { "Rockscale Cod", "Giant Clam Scorcho", "Jungle Stew", "Roast Raptor", "Hot Wolf Ribs", "Carrion Surprise" },
		},
		{
			type = "USE",
			title = "Craft 35x Spotted Yellowtail",
			note = "Takes you from 230 to 280.",
			skill = { profession = "Cooking", from = 230, to = 280 },
			craft = { item = "Spotted Yellowtail", count = 35 },
			reagents = { { item = "Raw Spotted Yellowtail", qty = 1 } },
			source = "Recipe: Spotted Yellowtail",
			alternatives = { "Filet of Redgill", "Mithril Head Trout", "Cooked Glossy Mightfish", "Giant Clam Scorcho", "Jungle Stew", "Roast Raptor" },
		},
		{
			type = "USE",
			title = "Craft 10x Poached Sunscale Salmon",
			note = "Takes you from 280 to 300.",
			skill = { profession = "Cooking", from = 280, to = 300 },
			craft = { item = "Poached Sunscale Salmon", count = 10 },
			reagents = { { item = "Raw Sunscale Salmon", qty = 1 } },
			source = "Recipe: Poached Sunscale Salmon",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Cooking is maxed at 300.",
		},
	},
})
