-- Enchanting (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


TurtleGuide:RegisterQuestShellPlusGuide("Enchanting (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Enchanting (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 187 crafts in total).",
		},
		{
			type = "TRAIN",
			title = "Apprentice Enchanting (1-75)",
			note = "Magister Sylvus Silkspinner (Thalassian Highlands), Betty Quin (Stormwind City), Thonys Pillarstone (Ironforge), Lalina Summermoon (Darnassus)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Enchanting (50-150)",
			note = "Magister Sylvus Silkspinner (Thalassian Highlands), Gimble Thistlefuzz (Ironforge), Lucan Cordell (Stormwind City), Taladan (Darnassus)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Enchanting (125-225)",
			note = "Annora (Uldaman), Kitta Firewind (Elwynn Forest), Magister Sylvus Silkspinner (Thalassian Highlands), Gimble Thistlefuzz (Ironforge)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Enchanting (200-300)",
			note = "Annora (Uldaman), Kitta Firewind (Elwynn Forest)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Apprentice Enchanting (1-75)",
			note = "Mot Dawnstrider (Thunder Bluff), Malcomb Wynn (Undercity), Jhag (Orgrimmar), Vance Undergloom (Tirisfal Glades)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Enchanting (50-150)",
			note = "Godan (Orgrimmar), Lavinia Crowe (Undercity), Teg Dawnstrider (Thunder Bluff), Mot Dawnstrider (Thunder Bluff)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Enchanting (125-225)",
			note = "Annora (Uldaman), Hgarth (Stonetalon Mountains), Godan (Orgrimmar), Lavinia Crowe (Undercity)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Enchanting (200-300)",
			note = "Annora (Uldaman), Hgarth (Stonetalon Mountains)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Learn Enchanting (Apprentice)",
			note = "Skill 1-75",
		},
		{
			type = "USE",
			title = "Craft 40x Enchant Bracer - Minor Health",
			note = "Takes you from 1 to 71.",
			skill = { profession = "Enchanting", from = 1, to = 71 },
			craft = { item = "Enchant Bracer - Minor Health", count = 40 },
			reagents = { { item = "Strange Dust", qty = 1 } },
			source = "Auto-learned",
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Enchanting (Cap 150)",
			note = "Skill 50",
		},
		{
			type = "USE",
			title = "Craft 10x Enchant Chest - Minor Health",
			note = "Takes you from 71 to 78.",
			skill = { profession = "Enchanting", from = 71, to = 78 },
			craft = { item = "Enchant Chest - Minor Health", count = 10 },
			reagents = { { item = "Strange Dust", qty = 1 } },
			source = "Trainer",
			alternatives = { "Enchant Chest - Minor Mana", "Enchant Bracer - Minor Spirit", "Enchant Bracer - Minor Deflect", "Enchant Chest - Minor Absorption", "Enchant Cloak - Minor Resistance", "Enchant Bracer - Minor Stamina" },
		},
		{
			type = "USE",
			title = "Craft 10x Enchant Chest - Minor Mana",
			note = "Takes you from 78 to 85.",
			skill = { profession = "Enchanting", from = 78, to = 85 },
			craft = { item = "Enchant Chest - Minor Mana", count = 10 },
			reagents = { { item = "Lesser Magic Essence", qty = 1 } },
			source = "Recipe: Formula: Enchant Chest - Minor Mana",
			alternatives = { "Enchant Chest - Minor Health", "Enchant Bracer - Minor Spirit", "Enchant Bracer - Minor Deflect", "Enchant Chest - Minor Absorption", "Enchant Cloak - Minor Resistance", "Enchant Bracer - Minor Stamina" },
		},
		{
			type = "USE",
			title = "Craft 15x Enchant Bracer - Minor Spirit",
			note = "Takes you from 85 to 118.",
			skill = { profession = "Enchanting", from = 85, to = 118 },
			craft = { item = "Enchant Bracer - Minor Spirit", count = 15 },
			reagents = { { item = "Lesser Magic Essence", qty = 2 } },
			source = "Recipe: Formula: Enchant Bracer - Minor Spirit",
			alternatives = { "Enchant Chest - Minor Mana", "Enchant Bracer - Minor Deflect", "Enchant Bracer - Minor Stamina", "Enchant Chest - Minor Absorption", "Enchant Cloak - Minor Resistance", "Enchant Chest - Lesser Health" },
		},
		{
			type = "USE",
			title = "Craft 20x Enchant Bracer - Minor Strength",
			note = "Takes you from 118 to 133.",
			skill = { profession = "Enchanting", from = 118, to = 133 },
			craft = { item = "Enchant Bracer - Minor Strength", count = 20 },
			reagents = { { item = "Strange Dust", qty = 5 } },
			source = "Recipe: Formula: Enchant Bracer - Minor Strength",
			alternatives = { "Enchant Bracer - Minor Spirit", "Enchant Bracer - Minor Stamina", "Enchant Chest - Lesser Health", "Enchant Cloak - Minor Agility", "Enchant Chest - Lesser Mana", "Enchant Shield - Minor Stamina" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Enchanting (Cap 225)",
			note = "Skill 125",
		},
		{
			type = "USE",
			title = "Craft 17x Enchant Boots - Minor Stamina",
			note = "Takes you from 133 to 170.",
			skill = { profession = "Enchanting", from = 133, to = 170 },
			craft = { item = "Enchant Boots - Minor Stamina", count = 17 },
			reagents = { { item = "Strange Dust", qty = 8 } },
			source = "Recipe: Formula: Enchant Boots - Minor Stamina",
			alternatives = { "Enchant Bracer - Minor Strength", "Enchant Cloak - Minor Agility", "Enchant Bracer - Lesser Stamina", "Enchant Bracer - Lesser Spirit", "Enchant Chest - Lesser Mana", "Enchant Shield - Lesser Protection" },
		},
		{
			type = "USE",
			title = "Craft 15x Enchant Bracer - Spirit",
			note = "Takes you from 170 to 205.",
			skill = { profession = "Enchanting", from = 170, to = 205 },
			craft = { item = "Enchant Bracer - Spirit", count = 15 },
			reagents = { { item = "Lesser Mystic Essence", qty = 1 } },
			source = "Trainer",
			alternatives = { "Enchant Boots - Minor Stamina", "Enchant Cloak - Minor Agility", "Enchant Bracer - Lesser Intellect", "Enchant Shield - Lesser Stamina", "Enchant Boots - Lesser Agility", "Enchant Bracer - Lesser Stamina" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Enchanting (Cap 300)",
			note = "Skill 200",
		},
		{
			type = "USE",
			title = "Craft 20x Enchant Cloak - Resistance",
			note = "Takes you from 205 to 245.",
			skill = { profession = "Enchanting", from = 205, to = 245 },
			craft = { item = "Enchant Cloak - Resistance", count = 20 },
			reagents = { { item = "Lesser Nether Essence", qty = 1 } },
			source = "Trainer",
			alternatives = { "Enchant Bracer - Strength", "Enchant Chest - Greater Mana", "Enchant Bracer - Spirit", "Enchant Shield - Spirit", "Enchant Bracer - Lesser Intellect", "Enchant Shield - Lesser Stamina" },
		},
		{
			type = "USE",
			title = "Craft 20x Enchant Bracer - Greater Stamina",
			note = "Takes you from 245 to 285.",
			skill = { profession = "Enchanting", from = 245, to = 285 },
			craft = { item = "Enchant Bracer - Greater Stamina", count = 20 },
			reagents = { { item = "Dream Dust", qty = 5 } },
			source = "Recipe: Formula: Enchant Bracer - Greater Stamina",
			alternatives = { "Enchant Cloak - Resistance", "Enchant Boots - Agility", "Enchant Gloves - Agility", "Enchant Bracer - Intellect", "Enchant Cloak - Lesser Agility", "Enchant Shield - Greater Spirit" },
		},
		{
			type = "USE",
			title = "Craft 20x Enchant Shield - Greater Stamina",
			note = "Takes you from 285 to 300.",
			skill = { profession = "Enchanting", from = 285, to = 300 },
			craft = { item = "Enchant Shield - Greater Stamina", count = 20 },
			reagents = { { item = "Dream Dust", qty = 10 } },
			source = "Recipe: Formula: Enchant Shield - Greater Stamina",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Enchanting is maxed at 300.",
		},
	},
})
