-- First Aid (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


TurtleGuide:RegisterQuestShellPlusGuide("First Aid (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "First Aid (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 295 crafts in total).",
		},
		{
			type = "NOTE",
			title = "Before you start",
			note = "Totals assume you follow the main route below without alternatives.",
		},
		{
			type = "TRAIN",
			title = "Apprentice First Aid (1-75)",
			note = "Thamner Pol (Dun Morogh), Aelira Dawnhand (Thalassian Highlands), Michelle Belle (Elwynn Forest), Byancie (Teldrassil)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman First Aid (50-150)",
			note = "Thamner Pol (Dun Morogh), Aelira Dawnhand (Thalassian Highlands), Michelle Belle (Elwynn Forest), Byancie (Teldrassil)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert First Aid (125-225)",
			note = "Thamner Pol (Dun Morogh), Aelira Dawnhand (Thalassian Highlands), Michelle Belle (Elwynn Forest), Byancie (Teldrassil)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan First Aid (200-300)",
			note = "Doctor Gustaf VanHowzen (Dustwallow Marsh)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Apprentice First Aid (1-75)",
			note = "Leyna Dayton (Silverpine Forest), Nurse Neela (Tirisfal Glades), Vira Younghoof (Mulgore), Kana Togglebend (Blackstone Island)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman First Aid (50-150)",
			note = "Leyna Dayton (Silverpine Forest), Nurse Neela (Tirisfal Glades), Vira Younghoof (Mulgore), Kana Togglebend (Blackstone Island)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert First Aid (125-225)",
			note = "Leyna Dayton (Silverpine Forest), Nurse Neela (Tirisfal Glades), Vira Younghoof (Mulgore), Kana Togglebend (Blackstone Island)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan First Aid (200-300)",
			note = "Doctor Gregory Victor (Arathi Highlands)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Learn First Aid (Apprentice)",
			note = "Skill 1-50",
		},
		{
			type = "USE",
			title = "Craft 29x Linen Bandage",
			note = "Takes you from 1 to 45.",
			skill = { profession = "First Aid", from = 1, to = 45 },
			craft = { item = "Linen Bandage", count = 29 },
			reagents = { { item = "Linen Cloth", qty = 1 } },
			source = "Auto-learned",
		},
		{
			type = "TRAIN",
			title = "Train Journeyman First Aid (Cap 150)",
			note = "Skill 50",
		},
		{
			type = "USE",
			title = "Craft 5x Heavy Linen Bandage",
			note = "Takes you from 45 to 100.",
			skill = { profession = "First Aid", from = 45, to = 100 },
			craft = { item = "Heavy Linen Bandage", count = 5 },
			reagents = { { item = "Linen Cloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 20x Wool Bandage",
			note = "Takes you from 100 to 115.",
			skill = { profession = "First Aid", from = 100, to = 115 },
			craft = { item = "Wool Bandage", count = 20 },
			reagents = { { item = "Wool Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 46x Heavy Wool Bandage",
			note = "Takes you from 115 to 150.",
			skill = { profession = "First Aid", from = 115, to = 150 },
			craft = { item = "Heavy Wool Bandage", count = 46 },
			reagents = { { item = "Wool Cloth", qty = 2 } },
			source = "Trainer",
			alternatives = { "Wool Bandage", "Anti-Venom" },
		},
		{
			type = "TRAIN",
			title = "Train Expert First Aid (Cap 225)",
			note = "Skill 125",
		},
		{
			type = "USE",
			title = "Craft 39x Silk Bandage",
			note = "Takes you from 150 to 180.",
			skill = { profession = "First Aid", from = 150, to = 180 },
			craft = { item = "Silk Bandage", count = 39 },
			reagents = { { item = "Silk Cloth", qty = 1 } },
			source = "Trainer",
			alternatives = { "Heavy Wool Bandage", "Strong Anti-Venom" },
		},
		{
			type = "USE",
			title = "Craft 39x Heavy Silk Bandage",
			note = "Takes you from 180 to 210.",
			skill = { profession = "First Aid", from = 180, to = 210 },
			craft = { item = "Heavy Silk Bandage", count = 39 },
			reagents = { { item = "Silk Cloth", qty = 2 } },
			source = "Recipe: Manual: Heavy Silk Bandage",
			alternatives = { "Heavy Wool Bandage", "Silk Bandage", "Strong Anti-Venom" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan First Aid (Cap 300)",
			note = "Skill 200",
		},
		{
			type = "USE",
			title = "Craft 39x Mageweave Bandage",
			note = "Takes you from 210 to 240.",
			skill = { profession = "First Aid", from = 210, to = 240 },
			craft = { item = "Mageweave Bandage", count = 39 },
			reagents = { { item = "Mageweave Cloth", qty = 1 } },
			source = "Recipe: Manual: Mageweave Bandage",
		},
		{
			type = "USE",
			title = "Craft 26x Heavy Mageweave Bandage",
			note = "Takes you from 240 to 260.",
			skill = { profession = "First Aid", from = 240, to = 260 },
			craft = { item = "Heavy Mageweave Bandage", count = 26 },
			reagents = { { item = "Mageweave Cloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 39x Runecloth Bandage",
			note = "Takes you from 260 to 290.",
			skill = { profession = "First Aid", from = 260, to = 290 },
			craft = { item = "Runecloth Bandage", count = 39 },
			reagents = { { item = "Runecloth", qty = 1 } },
			source = "Trainer",
			alternatives = { "Mageweave Bandage", "Heavy Mageweave Bandage", "Powerful Smelling Salts" },
		},
		{
			type = "USE",
			title = "Craft 13x Heavy Runecloth Bandage",
			note = "Takes you from 290 to 300.",
			skill = { profession = "First Aid", from = 290, to = 300 },
			craft = { item = "Heavy Runecloth Bandage", count = 13 },
			reagents = { { item = "Runecloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "First Aid is maxed at 300.",
		},
	},
})
