-- Jewelcrafting (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


TurtleGuide:RegisterQuestShellPlusGuide("Jewelcrafting (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Jewelcrafting (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 241 crafts in total).",
		},
		{
			type = "NOTE",
			title = "Before you start",
			note = "Totals assume you follow the main route below without alternatives.",
		},
		{
			type = "TRAIN",
			title = "Apprentice Jewelcrafting (1-70)",
			note = "Brandon Fencer (Stormwind City), Frabus Barleymantle (Ironforge), Kalvan Fencer (Stormwind City), Ranellius Pureheart (Alah'Thalas)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Jewelcrafting (50-150)",
			note = "Kalvan Fencer (Stormwind City), Ethennar Somberfall (Alah'Thalas), Torvag Thunderhand (Ironforge), Mayva Togview (Ironforge)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Jewelcrafting (125-225)",
			note = "Fanzy Sparkspring (Tanaris), Mayva Togview (Ironforge), Kalvan Fencer (Stormwind City), Ethennar Somberfall (Alah'Thalas)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Jewelcrafting (200-300)",
			note = "The Artificer (Desolace), Thegren (Badlands), Fanzy Sparkspring (Tanaris)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Apprentice Jewelcrafting (1-70)",
			note = "Asoran (Orgrimmar), Edgar Tullson (Undercity), Gelpan Rizspark (Durotar), Mayvelle Tonberg (Undercity)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Jewelcrafting (50-150)",
			note = "Mayvelle Tonberg (Undercity), Tacknazz Copperfire (Durotar), Kalnag (Orgrimmar), Gulmire Fartower (Undercity)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Jewelcrafting (125-225)",
			note = "Fanzy Sparkspring (Tanaris), Gulmire Fartower (Undercity), Mayvelle Tonberg (Undercity), Tacknazz Copperfire (Durotar)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Jewelcrafting (200-300)",
			note = "The Artificer (Desolace), Thegren (Badlands), Fanzy Sparkspring (Tanaris)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Learn Jewelcrafting (Apprentice)",
			note = "Skill 1-50",
		},
		{
			type = "USE",
			title = "Craft 20x Rough Gritted Paper",
			note = "Takes you from 1 to 25.",
			skill = { profession = "Jewelcrafting", from = 1, to = 25 },
			craft = { item = "Rough Gritted Paper", count = 20 },
			reagents = { { item = "Linen Cloth", qty = 1 }, { item = "Rough Stone", qty = 1 } },
			source = "Auto-learned",
			alternatives = { "Rough Copper Ring", "Copper Bangle" },
		},
		{
			type = "USE",
			title = "Craft 20x Rough Gemstone Cluster",
			note = "Takes you from 25 to 50.",
			skill = { profession = "Jewelcrafting", from = 25, to = 50 },
			craft = { item = "Rough Gemstone Cluster", count = 20 },
			reagents = { { item = "Rough Gritted Paper", qty = 1 }, { item = "Copper Ore", qty = 1 } },
			source = "Trainer",
			alternatives = { "Rough Gritted Paper", "Rough Copper Ring", "Malachite Ring", "Sturdy Copper Ring", "Bright Copper Ring", "Copper Bangle" },
		},
		{
			type = "USE",
			title = "Craft 10x Malachite Ring",
			note = "Takes you from 50 to 70.",
			skill = { profession = "Jewelcrafting", from = 50, to = 70 },
			craft = { item = "Malachite Ring", count = 10 },
			reagents = { { item = "Rough Copper Ring", qty = 1 }, { item = "Malachite", qty = 1 } },
			source = "Recipe: Plans: Malachite Ring",
			alternatives = { "Rough Gemstone Cluster", "Sturdy Copper Ring", "Bright Copper Ring", "Bulky Copper Ring", "Copper Staff" },
		},
		{
			type = "USE",
			title = "Craft 5x Coarse Gritted Paper",
			note = "Takes you from 70 to 75.",
			skill = { profession = "Jewelcrafting", from = 70, to = 75 },
			craft = { item = "Coarse Gritted Paper", count = 5 },
			reagents = { { item = "Wool Cloth", qty = 2 }, { item = "Coarse Stone", qty = 2 } },
			source = "Trainer",
			alternatives = { "Malachite Ring", "Copper Staff", "Encrusted Copper Bangle", "Amber Ring", "Bright Copper Necklace", "Tigercrest Ring" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Jewelcrafting (Cap 150)",
			note = "Skill 50",
		},
		{
			type = "USE",
			title = "Craft 10x Ebon Ring",
			note = "Takes you from 75 to 85.",
			skill = { profession = "Jewelcrafting", from = 75, to = 85 },
			craft = { item = "Ebon Ring", count = 10 },
			reagents = { { item = "Rough Copper Ring", qty = 1 }, { item = "Weak Flux", qty = 3 }, { item = "Rough Gritted Paper", qty = 2 } },
			source = "Recipe: Plans: Ebon Ring",
			alternatives = { "Malachite Ring", "Coarse Gritted Paper", "Encrusted Copper Bangle", "Amber Ring", "Bright Copper Necklace", "Tigercrest Ring" },
		},
		{
			type = "USE",
			title = "Craft 20x The King's Conviction",
			note = "Takes you from 85 to 115.",
			skill = { profession = "Jewelcrafting", from = 85, to = 115 },
			craft = { item = "The King's Conviction", count = 20 },
			reagents = { { item = "Rough Copper Ring", qty = 1 }, { item = "Weak Flux", qty = 1 }, { item = "Peacebloom", qty = 4 } },
			source = "Recipe: Plans: The King's Conviction",
			alternatives = { "Ebon Ring", "Coarse Gritted Paper", "Gloomweed Bindings", "Gleaming Chain", "Amber Ring", "Bright Copper Necklace" },
		},
		{
			type = "USE",
			title = "Craft 5x Gloomweed Bindings",
			note = "Takes you from 115 to 125.",
			skill = { profession = "Jewelcrafting", from = 115, to = 125 },
			craft = { item = "Gloomweed Bindings", count = 5 },
			reagents = { { item = "Copper Bar", qty = 6 }, { item = "Peacebloom", qty = 2 }, { item = "Polishing Oil", qty = 1 } },
			source = "Recipe: Plans: Gloomweed Bindings",
			alternatives = { "The King's Conviction", "Gleaming Chain", "Shimmering Bronze Ring", "Shadowmoon Orb", "Ocean's Wrath", "Earthrock Loop" },
		},
		{
			type = "USE",
			title = "Craft 15x Coarse Gemstone Cluster",
			note = "Takes you from 125 to 143.",
			skill = { profession = "Jewelcrafting", from = 125, to = 143 },
			craft = { item = "Coarse Gemstone Cluster", count = 15 },
			reagents = { { item = "Tin Ore", qty = 2 }, { item = "Coarse Gritted Paper", qty = 2 } },
			source = "Trainer",
			alternatives = { "Gloomweed Bindings", "Rough Silver Ring", "Ocean's Wrath", "Earthrock Loop", "Medallion of Flame", "Hydrathorn Bracers" },
		},
		{
			type = "USE",
			title = "Craft 10x Gloomweed Bindings",
			note = "Takes you from 143 to 150.",
			skill = { profession = "Jewelcrafting", from = 143, to = 150 },
			craft = { item = "Gloomweed Bindings", count = 10 },
			reagents = { { item = "Copper Bar", qty = 6 }, { item = "Peacebloom", qty = 2 }, { item = "Polishing Oil", qty = 1 } },
			source = "Recipe: Plans: Gloomweed Bindings",
			alternatives = { "Coarse Gemstone Cluster", "Rough Silver Ring", "Medallion of Flame", "Hydrathorn Bracers", "Bronze Cuffed Bangles", "Circlet of Dampening" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Jewelcrafting (Cap 225)",
			note = "Skill 125",
		},
		{
			type = "USE",
			title = "Craft 15x Harpy Talon Ring",
			note = "Takes you from 150 to 175.",
			skill = { profession = "Jewelcrafting", from = 150, to = 175 },
			craft = { item = "Harpy Talon Ring", count = 15 },
			reagents = { { item = "Rough Bronze Ring", qty = 1 }, { item = "Sharp Claw", qty = 4 }, { item = "Coarse Gritted Paper", qty = 2 } },
			source = "Recipe: Plans: Harpy Talon Ring",
			alternatives = { "Rough Silver Ring", "Rough Iron Ring", "Circlet of Dampening", "Heavy Gritted Paper", "Ring of Midnight", "Heavy Gemstone Cluster" },
		},
		{
			type = "USE",
			title = "Craft 4x Rough Mithril Ring",
			note = "Takes you from 175 to 178.",
			skill = { profession = "Jewelcrafting", from = 175, to = 178 },
			craft = { item = "Rough Mithril Ring", count = 4 },
			reagents = { { item = "Mithril Bar", qty = 2 } },
			source = "Trainer",
			alternatives = { "Harpy Talon Ring", "Centaur Hoof Circlet", "Quartz Halo", "Jade Harmony Circlet", "Obsidian Brooch", "Pure Shining Moonstone" },
		},
		{
			type = "USE",
			title = "Craft 2x Centaur Hoof Circlet",
			note = "Takes you from 178 to 190.",
			skill = { profession = "Jewelcrafting", from = 178, to = 190 },
			craft = { item = "Centaur Hoof Circlet", count = 2 },
			reagents = { { item = "Rough Iron Ring", qty = 1 }, { item = "Elemental Earth", qty = 1 }, { item = "Strong Flux", qty = 1 }, { item = "Coarse Gritted Paper", qty = 2 } },
			source = "Recipe: Plans: Centaur Hoof Circlet",
			alternatives = { "Harpy Talon Ring", "Rough Mithril Ring", "Quartz Halo", "Jade Harmony Circlet", "Obsidian Brooch", "Pure Shining Moonstone" },
		},
		{
			type = "USE",
			title = "Craft 10x Ironbloom Ring",
			note = "Takes you from 190 to 200.",
			skill = { profession = "Jewelcrafting", from = 190, to = 200 },
			craft = { item = "Ironbloom Ring", count = 10 },
			reagents = { { item = "Rough Iron Ring", qty = 1 }, { item = "Iron Bar", qty = 2 }, { item = "Heavy Stone", qty = 6 }, { item = "Wild Steelbloom", qty = 1 }, { item = "Heavy Gritted Paper", qty = 2 } },
			source = "Trainer",
			alternatives = { "Centaur Hoof Circlet", "Quartz Halo", "Facetted Moonstone Brooch", "Ancient Dwarven Gemstone", "Jade Harmony Circlet", "Obsidian Brooch" },
		},
		{
			type = "USE",
			title = "Craft 7x Solid Gritted Paper",
			note = "Takes you from 200 to 205.",
			skill = { profession = "Jewelcrafting", from = 200, to = 205 },
			craft = { item = "Solid Gritted Paper", count = 7 },
			reagents = { { item = "Mageweave Cloth", qty = 3 }, { item = "Solid Stone", qty = 3 } },
			source = "Trainer",
			alternatives = { "Ironbloom Ring", "Solid Gemstone Cluster", "Facetted Moonstone Brooch", "Ancient Dwarven Gemstone", "Draenethyst Baton", "Jade Harmony Circlet" },
		},
		{
			type = "USE",
			title = "Craft 13x Ironbloom Ring",
			note = "Takes you from 205 to 215.",
			skill = { profession = "Jewelcrafting", from = 205, to = 215 },
			craft = { item = "Ironbloom Ring", count = 13 },
			reagents = { { item = "Rough Iron Ring", qty = 1 }, { item = "Iron Bar", qty = 2 }, { item = "Heavy Stone", qty = 6 }, { item = "Wild Steelbloom", qty = 1 }, { item = "Heavy Gritted Paper", qty = 2 } },
			source = "Trainer",
			alternatives = { "Solid Gritted Paper", "Solid Gemstone Cluster", "Facetted Moonstone Brooch", "Draenethyst Baton", "Sharpened Citrine Gemstone", "Radiant Ember Gemstone" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Jewelcrafting (Cap 300)",
			note = "Skill 200",
		},
		{
			type = "USE",
			title = "Craft 10x Draenethyst Baton",
			note = "Takes you from 215 to 235.",
			skill = { profession = "Jewelcrafting", from = 215, to = 235 },
			craft = { item = "Draenethyst Baton", count = 10 },
			reagents = { { item = "Mithril Bar", qty = 4 }, { item = "Imperfect Draenethyst Fragment", qty = 1 }, { item = "Shimmering Oil", qty = 1 } },
			source = "Recipe: Plans: Draenethyst Baton",
			alternatives = { "Ironbloom Ring", "Bloodfire Circlet", "Marine Root", "Marine's Demise", "Greater Binding Signet", "Smoldering Brooch" },
		},
		{
			type = "USE",
			title = "Craft 10x Rough Thorium Ring",
			note = "Takes you from 235 to 250.",
			skill = { profession = "Jewelcrafting", from = 235, to = 250 },
			craft = { item = "Rough Thorium Ring", count = 10 },
			reagents = { { item = "Thorium Bar", qty = 2 } },
			source = "Trainer",
			alternatives = { "Dense Gemstone Cluster", "Draenethyst Baton", "Runed Truesilver Ring", "Bloodfire Circlet", "Greater Binding Signet", "Smoldering Brooch" },
		},
		{
			type = "USE",
			title = "Craft 10x Dense Gritted Paper",
			note = "Takes you from 250 to 260.",
			skill = { profession = "Jewelcrafting", from = 250, to = 260 },
			craft = { item = "Dense Gritted Paper", count = 10 },
			reagents = { { item = "Runecloth", qty = 3 }, { item = "Dense Stone", qty = 3 } },
			source = "Trainer",
			alternatives = { "Rough Thorium Ring", "Runed Truesilver Ring", "Skyfire Jewel", "Stellar Gemguards", "Emberstone Studded Ring", "Golden Scepter of Authority" },
		},
		{
			type = "USE",
			title = "Craft 5x Gloomy Diamond Gemstone",
			note = "Takes you from 260 to 268.",
			skill = { profession = "Jewelcrafting", from = 260, to = 268 },
			craft = { item = "Gloomy Diamond Gemstone", count = 5 },
			reagents = { { item = "Black Diamond", qty = 1 }, { item = "Solid Gritted Paper", qty = 5 }, { item = "Gemstone Oil", qty = 1 } },
			source = "Recipe: Plans: Gloomy Diamond Gemstone",
			alternatives = { "Dense Gritted Paper", "Skyfire Jewel", "Radiant Thorium Twilight", "Stellar Gemguards", "Golden Scepter of Authority", "Cinderfall Band" },
		},
		{
			type = "USE",
			title = "Craft 10x Skyfire Jewel",
			note = "Takes you from 268 to 275.",
			skill = { profession = "Jewelcrafting", from = 268, to = 275 },
			craft = { item = "Skyfire Jewel", count = 10 },
			reagents = { { item = "Rough Thorium Ring", qty = 1 }, { item = "Pure Moonstone", qty = 3 }, { item = "Elemental Air", qty = 3 } },
			source = "Recipe: Plans: Skyfire Jewel",
			alternatives = { "Gloomy Diamond Gemstone", "Dense Gritted Paper", "Radiant Thorium Twilight", "Stellar Gemguards", "Golden Scepter of Authority", "Cinderfall Band" },
		},
		{
			type = "USE",
			title = "Craft 4x Unstable Arcane Gemstone",
			note = "Takes you from 275 to 278.",
			skill = { profession = "Jewelcrafting", from = 275, to = 278 },
			craft = { item = "Unstable Arcane Gemstone", count = 4 },
			reagents = { { item = "Arcane Crystal", qty = 1 }, { item = "Arcane Essence", qty = 1 }, { item = "Gemstone Oil", qty = 1 } },
			source = "Trainer",
			alternatives = { "Skyfire Jewel", "Radiant Thorium Twilight", "Stellar Gemguards", "Golden Scepter of Authority", "Cinderfall Band", "Crystalfire Armlets" },
		},
		{
			type = "USE",
			title = "Craft 3x Skyfire Jewel",
			note = "Takes you from 278 to 280.",
			skill = { profession = "Jewelcrafting", from = 278, to = 280 },
			craft = { item = "Skyfire Jewel", count = 3 },
			reagents = { { item = "Rough Thorium Ring", qty = 1 }, { item = "Pure Moonstone", qty = 3 }, { item = "Elemental Air", qty = 3 } },
			source = "Recipe: Plans: Skyfire Jewel",
			alternatives = { "Unstable Arcane Gemstone", "Radiant Thorium Twilight", "Stellar Gemguards", "Golden Scepter of Authority", "Cinderfall Band", "Crystalfire Armlets" },
		},
		{
			type = "USE",
			title = "Craft 13x Cinderfall Band",
			note = "Takes you from 280 to 290.",
			skill = { profession = "Jewelcrafting", from = 280, to = 290 },
			craft = { item = "Cinderfall Band", count = 13 },
			reagents = { { item = "Rough Thorium Ring", qty = 1 }, { item = "Emberstone", qty = 1 }, { item = "Star Ruby", qty = 1 }, { item = "Heart of Fire", qty = 1 }, { item = "Gemstone Oil", qty = 1 } },
			source = "Recipe: Plans: Cinderfall Band",
			alternatives = { "Radiant Thorium Twilight", "Stellar Gemguards", "Crystalfire Armlets", "Mithril Blackstone Necklace", "Blue Starfire", "Moonlit Charm" },
		},
		{
			type = "USE",
			title = "Craft 10x Dark Iron Signet Ring",
			note = "Takes you from 290 to 300.",
			skill = { profession = "Jewelcrafting", from = 290, to = 300 },
			craft = { item = "Dark Iron Signet Ring", count = 10 },
			reagents = { { item = "Dark Iron Bar", qty = 4 }, { item = "Heart of Fire", qty = 8 }, { item = "Blood of the Mountain", qty = 2 } },
			source = "Recipe: Plans: Dark Iron Signet Ring",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Jewelcrafting is maxed at 300.",
		},
	},
})
