-- Leatherworking (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


TurtleGuide:RegisterQuestShellPlusGuide("Leatherworking (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Leatherworking (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 242 crafts in total).",
		},
		{
			type = "NOTE",
			title = "Before you start",
			note = "Totals assume you follow the main route below without alternatives.",
		},
		{
			type = "TRAIN",
			title = "Apprentice Leatherworking (1-60)",
			note = "Shandlar Thethis (Alah'Thalas), Adele Fielder (Elwynn Forest), Darianna (Darnassus), Gretta Finespindle (Ironforge)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Leatherworking (50-150)",
			note = "Shandlar Thethis (Alah'Thalas), Faldron (Darnassus), Fimble Finespindle (Ironforge), Simon Tanner (Stormwind City)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Leatherworking (125-225)",
			note = "Telonis (Darnassus), Peter Galen (Azshara), Master Craftsman T'kalpa (Moonwhisper Coast), Sarah Tanner (Searing Gorge)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Leatherworking (200-300)",
			note = "Drakk Stonehand (The Hinterlands), Caryssia Moonhunter (Feralas), Peter Galen (Azshara), Telonis (Darnassus)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Apprentice Leatherworking (1-60)",
			note = "Zantiki (The Barrens), Chaw Stronghide (Mulgore), Dan Golthas (Undercity), Mak (Thunder Bluff)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Leatherworking (50-150)",
			note = "Arthur Moore (Undercity), Brawn (Stranglethorn Vale), Karolek (Orgrimmar), Tarn (Thunder Bluff)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Leatherworking (125-225)",
			note = "Thorkaf Dragoneye (Badlands), Master Craftsman T'kalpa (Moonwhisper Coast), Brumn Winterhoof (Arathi Highlands), Una (Thunder Bluff)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Leatherworking (200-300)",
			note = "Hahrana Ironhide (Feralas), Raz'Dag (Arathi Highlands), Se'Jib (Stranglethorn Vale), Una (Thunder Bluff)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Learn Leatherworking (Apprentice)",
			note = "Skill 1-50",
		},
		{
			type = "USE",
			title = "Craft 29x Light Armor Kit",
			note = "Takes you from 1 to 45.",
			skill = { profession = "Leatherworking", from = 1, to = 45 },
			craft = { item = "Light Armor Kit", count = 29 },
			reagents = { { item = "Light Leather", qty = 1 } },
			source = "Auto-learned",
			alternatives = { "Light Leather", "Handstitched Leather Boots", "Handstitched Leather Cloak", "Handstitched Leather Bracers", "Handstitched Leather Vest" },
		},
		{
			type = "USE",
			title = "Craft 13x Handstitched Leather Boots",
			note = "Takes you from 45 to 55.",
			skill = { profession = "Leatherworking", from = 45, to = 55 },
			craft = { item = "Handstitched Leather Boots", count = 13 },
			reagents = { { item = "Light Leather", qty = 2 }, { item = "Coarse Thread", qty = 1 } },
			source = "Auto-learned",
			alternatives = { "Light Armor Kit", "Handstitched Leather Cloak", "Handstitched Leather Bracers", "Handstitched Leather Vest", "Small Leather Ammo Pouch", "Cured Light Hide" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Leatherworking (Cap 150)",
			note = "Skill 50",
		},
		{
			type = "USE",
			title = "Craft 30x Embossed Leather Gloves",
			note = "Takes you from 55 to 100.",
			skill = { profession = "Leatherworking", from = 55, to = 100 },
			craft = { item = "Embossed Leather Gloves", count = 30 },
			reagents = { { item = "Light Leather", qty = 3 }, { item = "Coarse Thread", qty = 2 } },
			source = "Trainer",
			alternatives = { "Light Armor Kit", "Handstitched Leather Boots", "Handstitched Leather Cloak", "Handstitched Leather Bracers", "Handstitched Leather Vest", "Small Leather Ammo Pouch" },
		},
		{
			type = "USE",
			title = "Craft 7x Medium Leather",
			note = "Takes you from 100 to 105.",
			skill = { profession = "Leatherworking", from = 100, to = 105 },
			craft = { item = "Medium Leather", count = 7 },
			reagents = { { item = "Light Leather", qty = 4 } },
			source = "Trainer",
			alternatives = { "Embossed Leather Gloves", "Embossed Leather Cloak", "Fine Leather Belt", "Light Leather Bracers", "Fine Leather Boots", "White Leather Jerkin" },
		},
		{
			type = "USE",
			title = "Craft 5x Fine Leather Belt",
			note = "Takes you from 105 to 125.",
			skill = { profession = "Leatherworking", from = 105, to = 125 },
			craft = { item = "Fine Leather Belt", count = 5 },
			reagents = { { item = "Light Leather", qty = 6 }, { item = "Coarse Thread", qty = 2 } },
			source = "Trainer",
			alternatives = { "Embossed Leather Gloves", "Medium Leather", "Embossed Leather Cloak", "Light Leather Bracers", "Fine Leather Boots", "Embossed Leather Boots" },
		},
		{
			type = "USE",
			title = "Craft 13x Fine Leather Boots",
			note = "Takes you from 125 to 135.",
			skill = { profession = "Leatherworking", from = 125, to = 135 },
			craft = { item = "Fine Leather Boots", count = 13 },
			reagents = { { item = "Light Leather", qty = 7 }, { item = "Coarse Thread", qty = 2 } },
			source = "Recipe: Pattern: Fine Leather Boots",
			alternatives = { "Fine Leather Belt", "Light Leather Bracers", "Cured Medium Hide", "Fine Leather Gloves", "Fine Leather Cloak", "Medium Armor Kit" },
		},
		{
			type = "USE",
			title = "Craft 7x Light Leather Pants",
			note = "Takes you from 135 to 140.",
			skill = { profession = "Leatherworking", from = 135, to = 140 },
			craft = { item = "Light Leather Pants", count = 7 },
			reagents = { { item = "Light Leather", qty = 10 }, { item = "Cured Light Hide", qty = 1 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Fine Leather Belt", "Fine Leather Boots", "Deviate Scale Cloak", "Dark Leather Boots", "Lynxstep Boots", "Moonglow Vest" },
		},
		{
			type = "USE",
			title = "Craft 10x Hillman's Shoulders",
			note = "Takes you from 140 to 150.",
			skill = { profession = "Leatherworking", from = 140, to = 150 },
			craft = { item = "Hillman's Shoulders", count = 10 },
			reagents = { { item = "Cured Medium Hide", qty = 1 }, { item = "Medium Leather", qty = 4 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Fine Leather Boots", "Light Leather Pants", "Deviate Scale Cloak", "Dark Leather Boots", "Lynxstep Boots", "Moonglow Vest" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Leatherworking (Cap 225)",
			note = "Skill 125",
		},
		{
			type = "USE",
			title = "Craft 10x Cured Heavy Hide",
			note = "Takes you from 150 to 165.",
			skill = { profession = "Leatherworking", from = 150, to = 165 },
			craft = { item = "Cured Heavy Hide", count = 10 },
			reagents = { { item = "Heavy Hide", qty = 1 }, { item = "Salt", qty = 3 } },
			source = "Trainer",
			alternatives = { "Heavy Leather", "Light Leather Pants", "Heavy Leather Ball", "Hillman's Shoulders", "Dark Leather Gloves", "Dark Leather Cloak" },
		},
		{
			type = "USE",
			title = "Craft 4x Hillman's Shoulders",
			note = "Takes you from 165 to 168.",
			skill = { profession = "Leatherworking", from = 165, to = 168 },
			craft = { item = "Hillman's Shoulders", count = 4 },
			reagents = { { item = "Cured Medium Hide", qty = 1 }, { item = "Medium Leather", qty = 4 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Cured Heavy Hide", "Dark Leather Gloves", "Dark Leather Belt", "Herbalist's Gloves", "Pilferer's Gloves", "Earthen Leather Shoulders" },
		},
		{
			type = "USE",
			title = "Craft 7x Herbalist's Gloves",
			note = "Takes you from 168 to 173.",
			skill = { profession = "Leatherworking", from = 168, to = 173 },
			craft = { item = "Herbalist's Gloves", count = 7 },
			reagents = { { item = "Medium Leather", qty = 8 }, { item = "Kingsblood", qty = 4 }, { item = "Fine Thread", qty = 2 } },
			source = "Recipe: Pattern: Herbalist's Gloves",
			alternatives = { "Cured Heavy Hide", "Hillman's Shoulders", "Dark Leather Gloves", "Dark Leather Belt", "Pilferer's Gloves", "Earthen Leather Shoulders" },
		},
		{
			type = "USE",
			title = "Craft 7x Pilferer's Gloves",
			note = "Takes you from 173 to 178.",
			skill = { profession = "Leatherworking", from = 173, to = 178 },
			craft = { item = "Pilferer's Gloves", count = 7 },
			reagents = { { item = "Medium Leather", qty = 10 }, { item = "Lucky Charm", qty = 2 }, { item = "Fine Thread", qty = 2 } },
			source = "Recipe: Pattern: Pilferer's Gloves",
			alternatives = { "Hillman's Shoulders", "Dark Leather Gloves", "Dark Leather Belt", "Herbalist's Gloves", "Earthen Leather Shoulders", "Heavy Armor Kit" },
		},
		{
			type = "USE",
			title = "Craft 3x Heavy Armor Kit",
			note = "Takes you from 178 to 180.",
			skill = { profession = "Leatherworking", from = 178, to = 180 },
			craft = { item = "Heavy Armor Kit", count = 3 },
			reagents = { { item = "Heavy Leather", qty = 5 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Hillman's Shoulders", "Dark Leather Gloves", "Herbalist's Gloves", "Pilferer's Gloves", "Earthen Leather Shoulders", "Hillman's Cloak" },
		},
		{
			type = "USE",
			title = "Craft 20x Cured Thick Hide",
			note = "Takes you from 180 to 200.",
			skill = { profession = "Leatherworking", from = 180, to = 200 },
			craft = { item = "Cured Thick Hide", count = 20 },
			reagents = { { item = "Thick Hide", qty = 1 }, { item = "Deeprock Salt", qty = 1 } },
			source = "Trainer",
			alternatives = { "Herbalist's Gloves", "Pilferer's Gloves", "Earthen Leather Shoulders", "Heavy Armor Kit", "Hillman's Leather Gloves", "Hillman's Cloak" },
		},
		{
			type = "USE",
			title = "Craft 4x Thick Leather",
			note = "Takes you from 200 to 203.",
			skill = { profession = "Leatherworking", from = 200, to = 203 },
			craft = { item = "Thick Leather", count = 4 },
			reagents = { { item = "Heavy Leather", qty = 6 } },
			source = "Trainer",
			alternatives = { "Guardian Gloves", "Green Leather Bracers", "Guardian Bracers", "Barbaric Shoulders", "Raptor Hide Belt", "Thick Armor Kit" },
		},
		{
			type = "USE",
			title = "Craft 7x Guardian Gloves",
			note = "Takes you from 203 to 220.",
			skill = { profession = "Leatherworking", from = 203, to = 220 },
			craft = { item = "Guardian Gloves", count = 7 },
			reagents = { { item = "Heavy Leather", qty = 4 }, { item = "Cured Heavy Hide", qty = 1 }, { item = "Silken Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Thick Leather", "Green Leather Bracers", "Guardian Bracers", "Barbaric Shoulders", "Raptor Hide Belt", "Thick Armor Kit" },
		},
		{
			type = "USE",
			title = "Craft 7x Guardian Bracers",
			note = "Takes you from 220 to 225.",
			skill = { profession = "Leatherworking", from = 220, to = 225 },
			craft = { item = "Guardian Bracers", count = 7 },
			reagents = { { item = "Heavy Leather", qty = 6 }, { item = "Cured Heavy Hide", qty = 2 }, { item = "Silken Thread", qty = 1 } },
			source = "Recipe: Pattern: Guardian Bracers",
			alternatives = { "Guardian Gloves", "Thick Armor Kit", "Nightscape Headband", "Grifter's Belt", "Grifter's Gauntlets", "Nightscape Tunic" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Leatherworking (Cap 300)",
			note = "Skill 200",
		},
		{
			type = "USE",
			title = "Craft 7x Thick Armor Kit",
			note = "Takes you from 225 to 230.",
			skill = { profession = "Leatherworking", from = 225, to = 230 },
			craft = { item = "Thick Armor Kit", count = 7 },
			reagents = { { item = "Thick Leather", qty = 5 }, { item = "Silken Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Guardian Gloves", "Guardian Bracers", "Nightscape Headband", "Nightscape Tunic", "Comfortable Leather Hat", "Green Whelp Bracers" },
		},
		{
			type = "USE",
			title = "Craft 20x Cured Rugged Hide",
			note = "Takes you from 230 to 255.",
			skill = { profession = "Leatherworking", from = 230, to = 255 },
			craft = { item = "Cured Rugged Hide", count = 20 },
			reagents = { { item = "Rugged Hide", qty = 1 }, { item = "Refined Deeprock Salt", qty = 1 } },
			source = "Trainer",
			alternatives = { "Guardian Bracers", "Thick Armor Kit", "Nightscape Headband", "Rugged Leather", "Nightscape Tunic", "Rugged Armor Kit" },
		},
		{
			type = "USE",
			title = "Craft 7x Rugged Armor Kit",
			note = "Takes you from 255 to 260.",
			skill = { profession = "Leatherworking", from = 255, to = 260 },
			craft = { item = "Rugged Armor Kit", count = 7 },
			reagents = { { item = "Rugged Leather", qty = 5 } },
			source = "Trainer",
			alternatives = { "Cured Rugged Hide", "Wild Leather Shoulders", "Wild Leather Helmet", "Tough Scorpid Gloves", "Nightscape Cloak", "Wild Leather Vest" },
		},
		{
			type = "USE",
			title = "Craft 5x Wild Leather Boots",
			note = "Takes you from 260 to 270.",
			skill = { profession = "Leatherworking", from = 260, to = 270 },
			craft = { item = "Wild Leather Boots", count = 5 },
			reagents = { { item = "Thick Leather", qty = 14 }, { item = "Wildvine", qty = 4 }, { item = "Cured Thick Hide", qty = 2 } },
			source = "Recipe: Pattern: Wild Leather Boots",
			alternatives = { "Rugged Armor Kit", "Wild Leather Helmet", "Tough Scorpid Gloves", "Nightscape Cloak", "Wild Leather Vest", "Thick Leather Ammo Pouch" },
		},
		{
			type = "USE",
			title = "Craft 20x Volcanic Leggings",
			note = "Takes you from 270 to 300.",
			skill = { profession = "Leatherworking", from = 270, to = 300 },
			craft = { item = "Volcanic Leggings", count = 20 },
			reagents = { { item = "Rugged Leather", qty = 6 }, { item = "Essence of Fire", qty = 1 }, { item = "Core of Earth", qty = 1 }, { item = "Rune Thread", qty = 1 } },
			source = "Recipe: Pattern: Volcanic Leggings",
			alternatives = { "Wild Leather Boots", "Wicked Leather Gauntlets", "Wicked Leather Bracers", "Nightscape Boots", "Wild Leather Leggings", "Wild Leather Cloak" },
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Leatherworking is maxed at 300.",
		},
	},
})
