-- Mining (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


TurtleGuide:RegisterQuestShellPlusGuide("Mining (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Mining (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 108 crafts in total).",
		},
		{
			type = "NOTE",
			title = "Before you start",
			note = "Totals assume you follow the main route below without alternatives.",
		},
		{
			type = "TRAIN",
			title = "Apprentice Mining (1-75)",
			note = "Dank Drizzlecut (Dun Morogh), Yarr Hammerstone (Dun Morogh), Brindel Morningsun (Alah'Thalas), Brock Stoneseeker (Loch Modan)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Mining (50-150)",
			note = "Dank Drizzlecut (Dun Morogh), Yarr Hammerstone (Dun Morogh), Brock Stoneseeker (Loch Modan), Matt Johnson (Duskwood)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Mining (125-225)",
			note = "Dank Drizzlecut (Dun Morogh), Yarr Hammerstone (Dun Morogh), Brock Stoneseeker (Loch Modan), Matt Johnson (Duskwood)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Mining (200-300)",
			note = "Dank Drizzlecut (Dun Morogh), Yarr Hammerstone (Dun Morogh), Brock Stoneseeker (Loch Modan), Matt Johnson (Duskwood)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Apprentice Mining (1-75)",
			note = "Tantaz Coppermud (Blackstone Island), Krunn (Durotar), Johan Focht (Silverpine Forest), Brek Stonehoof (Thunder Bluff)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Mining (50-150)",
			note = "Tantaz Coppermud (Blackstone Island), Krunn (Durotar), Johan Focht (Silverpine Forest), Brek Stonehoof (Thunder Bluff)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Mining (125-225)",
			note = "Tantaz Coppermud (Blackstone Island), Krunn (Durotar), Johan Focht (Silverpine Forest), Brek Stonehoof (Thunder Bluff)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Mining (200-300)",
			note = "Tantaz Coppermud (Blackstone Island), Krunn (Durotar), Johan Focht (Silverpine Forest), Brek Stonehoof (Thunder Bluff)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Learn Mining (Apprentice)",
			note = "Skill 1-50",
		},
		{
			type = "USE",
			title = "Craft 24x Copper Bar",
			note = "Takes you from 1 to 70.",
			skill = { profession = "Mining", from = 1, to = 70 },
			craft = { item = "Copper Bar", count = 24 },
			reagents = { { item = "Copper Ore", qty = 1 } },
			source = "Auto-learned",
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Mining (Cap 150)",
			note = "Skill 50",
		},
		{
			type = "USE",
			title = "Craft 26x Bronze Bar",
			note = "Takes you from 70 to 90.",
			skill = { profession = "Mining", from = 70, to = 90 },
			craft = { item = "Bronze Bar", count = 26 },
			reagents = { { item = "Copper Bar", qty = 1 }, { item = "Tin Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 10x Silver Bar",
			note = "Takes you from 90 to 113.",
			skill = { profession = "Mining", from = 90, to = 113 },
			craft = { item = "Silver Bar", count = 10 },
			reagents = { { item = "Silver Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 4x Bronze Bar",
			note = "Takes you from 113 to 115.",
			skill = { profession = "Mining", from = 113, to = 115 },
			craft = { item = "Bronze Bar", count = 4 },
			reagents = { { item = "Copper Bar", qty = 1 }, { item = "Tin Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 20x Silver Bar",
			note = "Takes you from 115 to 125.",
			skill = { profession = "Mining", from = 115, to = 125 },
			craft = { item = "Silver Bar", count = 20 },
			reagents = { { item = "Silver Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 5x Iron Bar",
			note = "Takes you from 125 to 140.",
			skill = { profession = "Mining", from = 125, to = 140 },
			craft = { item = "Iron Bar", count = 5 },
			reagents = { { item = "Iron Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "TRAIN",
			title = "Train Expert Mining (Cap 225)",
			note = "Skill 125",
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Iron Veins / Gold Veins)",
			note = "Takes you from 140 to 155. No learnable smelting recipe covers this range in the database.",
			skill = { profession = "Mining", from = 140, to = 155 },
		},
		{
			type = "USE",
			title = "Craft 15x Gold Bar",
			note = "Takes you from 155 to 185.",
			skill = { profession = "Mining", from = 155, to = 185 },
			craft = { item = "Gold Bar", count = 15 },
			reagents = { { item = "Gold Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "TRAIN",
			title = "Train Artisan Mining (Cap 300)",
			note = "Skill 200",
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Mithril Veins)",
			note = "Takes you from 185 to 230. No learnable smelting recipe covers this range in the database.",
			skill = { profession = "Mining", from = 185, to = 230 },
		},
		{
			type = "USE",
			title = "Craft 2x Truesilver Bar",
			note = "Takes you from 230 to 231.",
			skill = { profession = "Mining", from = 230, to = 231 },
			craft = { item = "Truesilver Bar", count = 2 },
			reagents = { { item = "Truesilver Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Truesilver Veins / Small Thorium Veins)",
			note = "Takes you from 231 to 250. No learnable smelting recipe covers this range in the database.",
			skill = { profession = "Mining", from = 231, to = 250 },
		},
		{
			type = "USE",
			title = "Craft 2x Thorium Bar",
			note = "Takes you from 250 to 251.",
			skill = { profession = "Mining", from = 250, to = 251 },
			craft = { item = "Thorium Bar", count = 2 },
			reagents = { { item = "Thorium Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Rich Thorium Veins)",
			note = "Takes you from 251 to 300. No learnable smelting recipe covers this range in the database.",
			skill = { profession = "Mining", from = 251, to = 300 },
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Mining is maxed at 300.",
		},
	},
})
