-- Survival (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


TurtleGuide:RegisterQuestShellPlusGuide("Survival (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Survival (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 245 crafts in total).",
		},
		{
			type = "TRAIN",
			title = "Apprentice Survival (1-75)",
			note = "Eissinn Cragbelly (Ironforge), Krennan Wildberry (Stormwind City), Rufus Hardwick (Stranglethorn Vale), Nallaeth (Darnassus)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Survival (50-150)",
			note = "Eissinn Cragbelly (Ironforge), Krennan Wildberry (Stormwind City), Nallaeth (Darnassus), Dyrohrinn Boulderhorn (Dun Morogh)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Survival (125-225)",
			note = "Rufus Hardwick (Stranglethorn Vale), Nerean Stagtree (Desolace), Eissinn Cragbelly (Ironforge), Krennan Wildberry (Stormwind City)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Survival (200-300)",
			note = "Rufus Hardwick (Stranglethorn Vale), Nerean Stagtree (Desolace)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Apprentice Survival (1-75)",
			note = "Brakan (Orgrimmar), Rufus Hardwick (Stranglethorn Vale), Swampwalker Krug (Swamp of Sorrows), Cynthessa Grimblood (Undercity)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Survival (50-150)",
			note = "Brakan (Orgrimmar), Cynthessa Grimblood (Undercity), Feebeld (Blackstone Island), Karolina Cloven (Tirisfal Glades)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Survival (125-225)",
			note = "Rufus Hardwick (Stranglethorn Vale), Swampwalker Krug (Swamp of Sorrows), Brakan (Orgrimmar), Cynthessa Grimblood (Undercity)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Survival (200-300)",
			note = "Rufus Hardwick (Stranglethorn Vale), Swampwalker Krug (Swamp of Sorrows)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Learn Survival (Apprentice)",
			note = "Skill 1-50",
		},
		{
			type = "USE",
			title = "Craft 9x Dim Torch",
			note = "Takes you from 1 to 13.",
			skill = { profession = "Survival", from = 1, to = 13 },
			craft = { item = "Dim Torch", count = 9 },
			reagents = { { item = "Unlit Poor Torch", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 17x Survivalist's Skinning Knife",
			note = "Takes you from 13 to 45.",
			skill = { profession = "Survival", from = 13, to = 45 },
			craft = { item = "Survivalist's Skinning Knife", count = 17 },
			reagents = { { item = "Rough Stone", qty = 2 }, { item = "Coarse Thread", qty = 1 }, { item = "Light Leather", qty = 1 } },
			source = "Trainer",
			alternatives = { "Dim Torch", "Bundle of Simple Sticks", "Driftwood Fishing Pole" },
		},
		{
			type = "USE",
			title = "Craft 7x Copper Lantern",
			note = "Takes you from 45 to 50.",
			skill = { profession = "Survival", from = 45, to = 50 },
			craft = { item = "Copper Lantern", count = 7 },
			reagents = { { item = "Dim Torch", qty = 1 }, { item = "Copper Bar", qty = 3 } },
			source = "Trainer",
			alternatives = { "Survivalist's Skinning Knife", "Driftwood Fishing Pole", "Simple Slingshot", "Makeshift Ration Bag", "Simple Herbalist's Backpack" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Survival (Cap 150)",
			note = "Skill 50",
		},
		{
			type = "USE",
			title = "Craft 20x Weak Healing Salve",
			note = "Takes you from 50 to 80.",
			skill = { profession = "Survival", from = 50, to = 80 },
			craft = { item = "Weak Healing Salve", count = 20 },
			reagents = { { item = "Refreshing Spring Water", qty = 1 }, { item = "Remedy Herbs", qty = 2 }, { item = "Simple Leaves", qty = 1 } },
			source = "Trainer",
			alternatives = { "Survivalist's Skinning Knife", "Copper Lantern", "Driftwood Fishing Pole", "Simple Slingshot", "Makeshift Ration Bag", "Simple Herbalist's Backpack" },
		},
		{
			type = "USE",
			title = "Craft 13x Makeshift Knife",
			note = "Takes you from 80 to 90.",
			skill = { profession = "Survival", from = 80, to = 90 },
			craft = { item = "Makeshift Knife", count = 13 },
			reagents = { { item = "Simple Wood", qty = 1 }, { item = "Copper Bar", qty = 3 }, { item = "Light Leather", qty = 2 } },
			source = "Trainer",
			alternatives = { "Weak Healing Salve", "Crude Fishing Rod", "Gardening Gloves" },
		},
		{
			type = "USE",
			title = "Craft 13x Crude Fishing Rod",
			note = "Takes you from 90 to 100.",
			skill = { profession = "Survival", from = 90, to = 100 },
			craft = { item = "Crude Fishing Rod", count = 13 },
			reagents = { { item = "Simple Wood", qty = 8 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Makeshift Knife", "Gardening Gloves", "Hunting Spear" },
		},
		{
			type = "USE",
			title = "Craft 20x Simple Fishing Lure",
			note = "Takes you from 100 to 130.",
			skill = { profession = "Survival", from = 100, to = 130 },
			craft = { item = "Simple Fishing Lure", count = 20 },
			reagents = { { item = "Clam Meat", qty = 1 }, { item = "Remedy Herbs", qty = 1 } },
			source = "Trainer",
			alternatives = { "Healing Salve", "Crude Fishing Rod", "Gardening Gloves", "Oakwood Bow", "Gardening Broom", "Hunting Spear" },
		},
		{
			type = "USE",
			title = "Craft 7x Sturdy Net",
			note = "Takes you from 130 to 135.",
			skill = { profession = "Survival", from = 130, to = 135 },
			craft = { item = "Sturdy Net", count = 7 },
			reagents = { { item = "Sturdy Rope", qty = 4 } },
			source = "Trainer",
			alternatives = { "Simple Fishing Lure", "Healing Salve", "Oakwood Bow", "Bundle of Bright Wood Sticks", "Blackmouth Fishing Trap", "Gardening Broom" },
		},
		{
			type = "USE",
			title = "Craft 7x Bundle of Bright Wood Sticks",
			note = "Takes you from 135 to 140.",
			skill = { profession = "Survival", from = 135, to = 140 },
			craft = { item = "Bundle of Bright Wood Sticks", count = 7 },
			reagents = { { item = "Bright Wood", qty = 3 } },
			source = "Trainer",
			alternatives = { "Simple Fishing Lure", "Healing Salve", "Sturdy Net", "Oakwood Bow", "Blackmouth Fishing Trap", "Reliable Fishing Rod" },
		},
		{
			type = "USE",
			title = "Craft 10x Throwable Net",
			note = "Takes you from 140 to 150.",
			skill = { profession = "Survival", from = 140, to = 150 },
			craft = { item = "Throwable Net", count = 10 },
			reagents = { { item = "Sturdy Net", qty = 1 }, { item = "Coarse Stone", qty = 4 } },
			source = "Trainer",
			alternatives = { "Bundle of Bright Wood Sticks", "Blackmouth Fishing Trap", "Reliable Fishing Rod", "Gardening Pitchfork", "Sturdy Cane", "Hat of the Junior Chef" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Survival (Cap 225)",
			note = "Skill 125",
		},
		{
			type = "USE",
			title = "Craft 20x Spicy Fishing Lure",
			note = "Takes you from 150 to 180.",
			skill = { profession = "Survival", from = 150, to = 180 },
			craft = { item = "Spicy Fishing Lure", count = 20 },
			reagents = { { item = "Tangy Clam Meat", qty = 1 }, { item = "Hot Spices", qty = 1 } },
			source = "Trainer",
			alternatives = { "Potent Healing Salve", "Throwable Net", "Blackmouth Fishing Trap", "Bright Wood Arrows", "Reliable Fishing Rod", "Gardening Pitchfork" },
		},
		{
			type = "USE",
			title = "Craft 7x Slowing Bolas",
			note = "Takes you from 180 to 185.",
			skill = { profession = "Survival", from = 180, to = 185 },
			craft = { item = "Slowing Bolas", count = 7 },
			reagents = { { item = "Heavy Stone", qty = 3 }, { item = "Sturdy Rope", qty = 2 } },
			source = "Trainer",
			alternatives = { "Spicy Fishing Lure", "Potent Healing Salve", "Bright Wood Arrows", "Cleaning Cloth", "Bundle of Shade Wood Sticks", "Firefin Fishing Trap" },
		},
		{
			type = "USE",
			title = "Craft 10x Cleaning Cloth",
			note = "Takes you from 185 to 195.",
			skill = { profession = "Survival", from = 185, to = 195 },
			craft = { item = "Cleaning Cloth", count = 10 },
			reagents = { { item = "Silk Cloth", qty = 2 }, { item = "Volatile Rum", qty = 1 } },
			source = "Trainer",
			alternatives = { "Spicy Fishing Lure", "Potent Healing Salve", "Slowing Bolas", "Bundle of Shade Wood Sticks", "Firefin Fishing Trap", "Iron Lantern" },
		},
		{
			type = "USE",
			title = "Craft 5x Jungle Remedy",
			note = "Takes you from 195 to 200.",
			skill = { profession = "Survival", from = 195, to = 200 },
			craft = { item = "Jungle Remedy", count = 5 },
			reagents = { { item = "Remedy Herbs", qty = 4 }, { item = "Shade Leaves", qty = 2 }, { item = "Junglevine Wine", qty = 1 } },
			source = "Recipe: Outline: Jungle Remedy",
			alternatives = { "Cleaning Cloth", "Firefin Fishing Trap", "Iron Lantern", "Sharpened Herb Sickle", "Snap Trap", "Edged Machete" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Survival (Cap 300)",
			note = "Skill 200",
		},
		{
			type = "USE",
			title = "Craft 5x Savory Fishing Lure",
			note = "Takes you from 200 to 205.",
			skill = { profession = "Survival", from = 200, to = 205 },
			craft = { item = "Savory Fishing Lure", count = 5 },
			reagents = { { item = "Zesty Clam Meat", qty = 1 }, { item = "Soothing Spices", qty = 2 } },
			source = "Trainer",
			alternatives = { "Jungle Remedy", "Cleaning Cloth", "Superior Healing Salve", "Firefin Fishing Trap", "Sharpened Herb Sickle", "Edged Machete" },
		},
		{
			type = "USE",
			title = "Craft 20x Nutritious Rations",
			note = "Takes you from 205 to 235.",
			skill = { profession = "Survival", from = 205, to = 235 },
			craft = { item = "Nutritious Rations", count = 20 },
			reagents = { { item = "Juicy Watermelon", qty = 2 }, { item = "Sour Mountain Berry", qty = 2 }, { item = "Plump Country Pumpkin", qty = 2 } },
			source = "Trainer",
			alternatives = { "Savory Fishing Lure", "Jungle Remedy", "Cleaning Cloth", "Shade Wood Arrows", "Superior Healing Salve", "Firefin Fishing Trap" },
		},
		{
			type = "USE",
			title = "Craft 5x Repaired Electro-Lantern",
			note = "Takes you from 235 to 240.",
			skill = { profession = "Survival", from = 235, to = 240 },
			craft = { item = "Repaired Electro-Lantern", count = 5 },
			reagents = { { item = "Broken Electro-lantern", qty = 5 }, { item = "Mithril Casing", qty = 1 }, { item = "Handful of Copper Bolts", qty = 1 }, { item = "Whirring Bronze Gizmo", qty = 1 }, { item = "Silver Contact", qty = 2 }, { item = "Gold Power Core", qty = 2 } },
			source = "Trainer",
			alternatives = { "Nutritious Rations", "Savory Fishing Lure", "Shade Wood Arrows", "Superior Healing Salve", "Bundle of Tropical Sticks", "Hiking Staff" },
		},
		{
			type = "USE",
			title = "Craft 20x Spiced Berries",
			note = "Takes you from 240 to 270.",
			skill = { profession = "Survival", from = 240, to = 270 },
			craft = { item = "Spiced Berries", count = 20 },
			reagents = { { item = "Sour Mountain Berry", qty = 1 }, { item = "Remedy Herbs", qty = 1 }, { item = "Hot Spices", qty = 2 } },
			source = "Trainer",
			alternatives = { "Nutritious Rations", "Aromatic Berries", "Shade Wood Arrows", "Repaired Electro-Lantern", "Bundle of Tropical Sticks", "Warped Recurve Bow" },
		},
		{
			type = "USE",
			title = "Craft 13x Premium Fishing Lure",
			note = "Takes you from 270 to 280.",
			skill = { profession = "Survival", from = 270, to = 280 },
			craft = { item = "Premium Fishing Lure", count = 13 },
			reagents = { { item = "Zesty Clam Meat", qty = 2 }, { item = "Molasses Firewater", qty = 1 } },
			source = "Trainer",
			alternatives = { "Spiced Berries", "Aromatic Berries", "Smooth Ironfeather Arrows", "Emergency Parachute", "Stabilizing Healing Salve", "Bundle of Star Wood Sticks" },
		},
		{
			type = "USE",
			title = "Craft 7x Smooth Ironfeather Arrows",
			note = "Takes you from 280 to 285.",
			skill = { profession = "Survival", from = 280, to = 285 },
			craft = { item = "Smooth Ironfeather Arrows", count = 7 },
			reagents = { { item = "Bundle of Tropical Sticks", qty = 1 }, { item = "Ironfeather", qty = 1 }, { item = "Thorium Bar", qty = 1 } },
			source = "Trainer",
			alternatives = { "Premium Fishing Lure", "Emergency Parachute", "Stabilizing Healing Salve", "Stonescale Fishing Trap", "Bundle of Star Wood Sticks", "Advanced Camouflage" },
		},
		{
			type = "USE",
			title = "Craft 10x Stonescale Fishing Trap",
			note = "Takes you from 285 to 300.",
			skill = { profession = "Survival", from = 285, to = 300 },
			craft = { item = "Stonescale Fishing Trap", count = 10 },
			reagents = { { item = "Bundle of Star Wood Sticks", qty = 2 }, { item = "Premium Fishing Lure", qty = 1 }, { item = "Sturdy Net", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Survival is maxed at 300.",
		},
	},
})
