-- Tailoring (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


TurtleGuide:RegisterQuestShellPlusGuide("Tailoring (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Tailoring (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 278 crafts in total).",
		},
		{
			type = "NOTE",
			title = "Before you start",
			note = "Totals assume you follow the main route below without alternatives.",
		},
		{
			type = "TRAIN",
			title = "Apprentice Tailoring (1-75)",
			note = "Velessa Brightstar (Alah'Thalas), Eldrin (Elwynn Forest), Uthrar Threx (Ironforge), Lawrence Schneider (Stormwind City)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Tailoring (1-150)",
			note = "Velessa Brightstar (Alah'Thalas), Sellandus (Stormwind City), Grarnik Goodstitch (Stranglethorn Vale), Jormund Stonebrow (Ironforge)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Tailoring (1-270)",
			note = "Georgio Bolero (Stormwind City), Timothy Worthington (Dustwallow Marsh), Meilosh (Timbermaw Tunnels), Jalane Ayrole (Stormwind City)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Tailoring (200-300)",
			note = "Georgio Bolero (Stormwind City), Timothy Worthington (Dustwallow Marsh), Meilosh (Timbermaw Tunnels)",
			faction = "Alliance",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Apprentice Tailoring (1-75)",
			note = "Bowen Brisboise (Tirisfal Glades), Snang (Orgrimmar), Victor Ward (Undercity), Kil'hala (The Barrens)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Journeyman Tailoring (1-150)",
			note = "Mahani (The Barrens), Rhiannon Davis (Undercity), Grarnik Goodstitch (Stranglethorn Vale), Magar (Orgrimmar)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Expert Tailoring (1-270)",
			note = "Josef Gregorian (Undercity), Meilosh (Timbermaw Tunnels), Daryl Stack (Hillsbrad Foothills), Josephine Lister (Undercity)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Artisan Tailoring (200-300)",
			note = "Josef Gregorian (Undercity), Meilosh (Timbermaw Tunnels)",
			faction = "Horde",
			optional = true,
		},
		{
			type = "TRAIN",
			title = "Learn Tailoring (Apprentice)",
			note = "Skill 1-50",
		},
		{
			type = "USE",
			title = "Craft 24x Bolt of Linen Cloth",
			note = "Takes you from 1 to 38.",
			skill = { profession = "Tailoring", from = 1, to = 38 },
			craft = { item = "Bolt of Linen Cloth", count = 24 },
			reagents = { { item = "Linen Cloth", qty = 2 } },
			source = "Auto-learned",
			alternatives = { "Linen Cloak", "Brown Linen Shirt", "Simple Linen Pants", "White Linen Shirt" },
		},
		{
			type = "USE",
			title = "Craft 7x Brown Linen Vest",
			note = "Takes you from 38 to 58.",
			skill = { profession = "Tailoring", from = 38, to = 58 },
			craft = { item = "Brown Linen Vest", count = 7 },
			reagents = { { item = "Bolt of Linen Cloth", qty = 1 }, { item = "Coarse Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Bolt of Linen Cloth", "Linen Belt", "Linen Cloak", "Brown Linen Shirt", "Simple Linen Pants", "White Linen Shirt" },
		},
		{
			type = "USE",
			title = "Craft 10x Linen Belt",
			note = "Takes you from 58 to 65.",
			skill = { profession = "Tailoring", from = 58, to = 65 },
			craft = { item = "Linen Belt", count = 10 },
			reagents = { { item = "Bolt of Linen Cloth", qty = 1 }, { item = "Coarse Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Brown Linen Vest", "Linen Cloak", "Brown Linen Shirt", "Simple Linen Pants", "White Linen Shirt", "Heavy Linen Gloves" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Tailoring (Cap 150)",
			note = "Skill 50",
		},
		{
			type = "USE",
			title = "Craft 17x Heavy Linen Gloves",
			note = "Takes you from 65 to 78.",
			skill = { profession = "Tailoring", from = 65, to = 78 },
			craft = { item = "Heavy Linen Gloves", count = 17 },
			reagents = { { item = "Bolt of Linen Cloth", qty = 2 }, { item = "Coarse Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Brown Linen Vest", "Linen Belt", "Brown Linen Pants", "Reinforced Linen Cape", "Red Linen Shirt", "Blue Linen Shirt" },
		},
		{
			type = "USE",
			title = "Craft 7x Reinforced Linen Cape",
			note = "Takes you from 78 to 103.",
			skill = { profession = "Tailoring", from = 78, to = 103 },
			craft = { item = "Reinforced Linen Cape", count = 7 },
			reagents = { { item = "Bolt of Linen Cloth", qty = 2 }, { item = "Coarse Thread", qty = 3 } },
			source = "Trainer",
			alternatives = { "Linen Belt", "Heavy Linen Gloves", "Brown Linen Pants", "Red Linen Shirt", "Blue Linen Shirt", "Simple Linen Boots" },
		},
		{
			type = "USE",
			title = "Craft 20x Woolen Cape",
			note = "Takes you from 103 to 118.",
			skill = { profession = "Tailoring", from = 103, to = 118 },
			craft = { item = "Woolen Cape", count = 20 },
			reagents = { { item = "Bolt of Woolen Cloth", qty = 1 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Reinforced Linen Cape", "Bolt of Woolen Cloth", "Linen Bag", "Red Linen Vest", "Blue Linen Vest", "Linen Boots" },
		},
		{
			type = "USE",
			title = "Craft 36x Gloves of Manathirst",
			note = "Takes you from 118 to 145.",
			skill = { profession = "Tailoring", from = 118, to = 145 },
			craft = { item = "Gloves of Manathirst", count = 36 },
			reagents = { { item = "Bolt of Linen Cloth", qty = 3 }, { item = "Fine Thread", qty = 2 }, { item = "Blue Dye", qty = 3 } },
			source = "Recipe: Pattern: Gloves of Manathirst",
			alternatives = { "Reinforced Linen Cape", "Woolen Cape", "Linen Boots", "Green Linen Bracers", "Green Linen Shirt", "Simple Kilt" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Tailoring (Cap 225)",
			note = "Skill 125",
		},
		{
			type = "USE",
			title = "Craft 11x Stylish Red Shirt",
			note = "Takes you from 145 to 153.",
			skill = { profession = "Tailoring", from = 145, to = 153 },
			craft = { item = "Stylish Red Shirt", count = 11 },
			reagents = { { item = "Bolt of Woolen Cloth", qty = 3 }, { item = "Red Dye", qty = 2 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "White Woolen Dress", "Double-stitched Woolen Shoulders", "Green Woolen Robe", "Red Woolen Bag", "Green Woolen Bag", "Blue Overalls" },
		},
		{
			type = "USE",
			title = "Craft 7x Red Woolen Bag",
			note = "Takes you from 153 to 158.",
			skill = { profession = "Tailoring", from = 153, to = 158 },
			craft = { item = "Red Woolen Bag", count = 7 },
			reagents = { { item = "Bolt of Woolen Cloth", qty = 4 }, { item = "Red Dye", qty = 1 }, { item = "Fine Thread", qty = 1 } },
			source = "Recipe: Pattern: Red Woolen Bag",
			alternatives = { "Stylish Red Shirt", "White Woolen Dress", "Double-stitched Woolen Shoulders", "Green Woolen Bag", "Blue Overalls", "Red Woolen Boots" },
		},
		{
			type = "USE",
			title = "Craft 7x Stylish Blue Shirt",
			note = "Takes you from 158 to 163.",
			skill = { profession = "Tailoring", from = 158, to = 163 },
			craft = { item = "Stylish Blue Shirt", count = 7 },
			reagents = { { item = "Bolt of Woolen Cloth", qty = 4 }, { item = "Blue Dye", qty = 2 }, { item = "Gray Dye", qty = 1 }, { item = "Fine Thread", qty = 1 } },
			source = "Recipe: Pattern: Stylish Blue Shirt",
			alternatives = { "Stylish Red Shirt", "White Woolen Dress", "Double-stitched Woolen Shoulders", "Red Woolen Bag", "Blue Overalls", "Colorful Kilt" },
		},
		{
			type = "USE",
			title = "Craft 7x Phoenix Gloves",
			note = "Takes you from 163 to 168.",
			skill = { profession = "Tailoring", from = 163, to = 168 },
			craft = { item = "Phoenix Gloves", count = 7 },
			reagents = { { item = "Bolt of Woolen Cloth", qty = 4 }, { item = "Iridescent Pearl", qty = 1 }, { item = "Fine Thread", qty = 4 }, { item = "Bleach", qty = 2 } },
			source = "Recipe: Pattern: Phoenix Gloves",
			alternatives = { "Stylish Red Shirt", "White Woolen Dress", "Double-stitched Woolen Shoulders", "Red Woolen Bag", "Stylish Blue Shirt", "Colorful Kilt" },
		},
		{
			type = "USE",
			title = "Craft 3x Dark Silk Shirt",
			note = "Takes you from 168 to 170.",
			skill = { profession = "Tailoring", from = 168, to = 170 },
			craft = { item = "Dark Silk Shirt", count = 3 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 2 }, { item = "Gray Dye", qty = 2 }, { item = "Fine Thread", qty = 1 } },
			source = "Recipe: Pattern: Dark Silk Shirt",
			alternatives = { "Stylish Red Shirt", "White Woolen Dress", "Double-stitched Woolen Shoulders", "Red Woolen Bag", "Stylish Blue Shirt", "Colorful Kilt" },
		},
		{
			type = "USE",
			title = "Craft 5x Formal White Shirt",
			note = "Takes you from 170 to 175.",
			skill = { profession = "Tailoring", from = 170, to = 175 },
			craft = { item = "Formal White Shirt", count = 5 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 3 }, { item = "Bleach", qty = 2 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Red Woolen Bag", "Stylish Blue Shirt", "Colorful Kilt", "Stylish Green Shirt", "Greater Adept's Robe", "Reinforced Woolen Shoulders" },
		},
		{
			type = "USE",
			title = "Craft 5x Bolt of Mageweave",
			note = "Takes you from 175 to 183.",
			skill = { profession = "Tailoring", from = 175, to = 183 },
			craft = { item = "Bolt of Mageweave", count = 5 },
			reagents = { { item = "Mageweave Cloth", qty = 5 } },
			source = "Trainer",
			alternatives = { "Stylish Blue Shirt", "Colorful Kilt", "Stylish Green Shirt", "Reinforced Woolen Shoulders", "Phoenix Gloves", "Phoenix Pants" },
		},
		{
			type = "USE",
			title = "Craft 3x Formal White Shirt",
			note = "Takes you from 183 to 185.",
			skill = { profession = "Tailoring", from = 183, to = 185 },
			craft = { item = "Formal White Shirt", count = 3 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 3 }, { item = "Bleach", qty = 2 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Bolt of Mageweave", "Phoenix Gloves", "Phoenix Pants", "Azure Silk Cloak", "Red Swashbuckler's Shirt", "Lesser Wizard's Robe" },
		},
		{
			type = "USE",
			title = "Craft 10x Azure Silk Cloak",
			note = "Takes you from 185 to 210.",
			skill = { profession = "Tailoring", from = 185, to = 210 },
			craft = { item = "Azure Silk Cloak", count = 10 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 3 }, { item = "Blue Dye", qty = 2 }, { item = "Fine Thread", qty = 2 } },
			source = "Recipe: Pattern: Azure Silk Cloak",
			alternatives = { "Formal White Shirt", "Red Swashbuckler's Shirt", "Azure Silk Gloves", "Small Silk Pack", "Spider Silk Slippers", "Earthen Vest" },
		},
		{
			type = "USE",
			title = "Craft 7x Crimson Silk Vest",
			note = "Takes you from 210 to 215.",
			skill = { profession = "Tailoring", from = 210, to = 215 },
			craft = { item = "Crimson Silk Vest", count = 7 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 4 }, { item = "Red Dye", qty = 2 }, { item = "Fine Thread", qty = 2 } },
			source = "Trainer",
			alternatives = { "Azure Silk Cloak", "Earthen Vest", "Long Silken Cloak", "Crimson Silk Pantaloons", "Black Mageweave Vest", "Black Mageweave Leggings" },
		},
		{
			type = "USE",
			title = "Craft 5x White Bandit Mask",
			note = "Takes you from 215 to 225.",
			skill = { profession = "Tailoring", from = 215, to = 225 },
			craft = { item = "White Bandit Mask", count = 5 },
			reagents = { { item = "Bolt of Mageweave", qty = 1 }, { item = "Bleach", qty = 1 }, { item = "Heavy Silken Thread", qty = 1 } },
			source = "Recipe: Pattern: White Bandit Mask",
			alternatives = { "Azure Silk Cloak", "Orange Mageweave Shirt", "Earthen Vest", "Crimson Silk Vest", "Long Silken Cloak", "Crimson Silk Pantaloons" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Tailoring (Cap 300)",
			note = "Skill 200",
		},
		{
			type = "USE",
			title = "Craft 13x Black Mageweave Vest",
			note = "Takes you from 225 to 235.",
			skill = { profession = "Tailoring", from = 225, to = 235 },
			craft = { item = "Black Mageweave Vest", count = 13 },
			reagents = { { item = "Bolt of Mageweave", qty = 2 }, { item = "Silken Thread", qty = 3 } },
			source = "Trainer",
			alternatives = { "White Bandit Mask", "Orange Mageweave Shirt", "Long Silken Cloak", "Crimson Silk Pantaloons", "Black Mageweave Leggings", "Green Silken Shoulders" },
		},
		{
			type = "USE",
			title = "Craft 13x Black Mageweave Gloves",
			note = "Takes you from 235 to 245.",
			skill = { profession = "Tailoring", from = 235, to = 245 },
			craft = { item = "Black Mageweave Gloves", count = 13 },
			reagents = { { item = "Bolt of Mageweave", qty = 2 }, { item = "Heavy Silken Thread", qty = 2 } },
			source = "Trainer",
			alternatives = { "Black Mageweave Vest", "Black Mageweave Leggings", "Azure Shoulders", "Black Mageweave Robe", "Red Mageweave Vest", "Red Mageweave Pants" },
		},
		{
			type = "USE",
			title = "Craft 7x Black Mageweave Headband",
			note = "Takes you from 245 to 250.",
			skill = { profession = "Tailoring", from = 245, to = 250 },
			craft = { item = "Black Mageweave Headband", count = 7 },
			reagents = { { item = "Bolt of Mageweave", qty = 3 }, { item = "Heavy Silken Thread", qty = 2 } },
			source = "Trainer",
			alternatives = { "Black Mageweave Vest", "Black Mageweave Leggings", "Black Mageweave Gloves", "Black Mageweave Robe", "Red Mageweave Vest", "Red Mageweave Pants" },
		},
		{
			type = "USE",
			title = "Craft 5x Bolt of Runecloth",
			note = "Takes you from 250 to 258.",
			skill = { profession = "Tailoring", from = 250, to = 258 },
			craft = { item = "Bolt of Runecloth", count = 5 },
			reagents = { { item = "Runecloth", qty = 5 } },
			source = "Trainer",
			alternatives = { "Black Mageweave Gloves", "Black Mageweave Robe", "Red Mageweave Vest", "Red Mageweave Pants", "Black Mageweave Headband", "Black Mageweave Shoulders" },
		},
		{
			type = "USE",
			title = "Craft 3x Black Mageweave Headband",
			note = "Takes you from 258 to 260.",
			skill = { profession = "Tailoring", from = 258, to = 260 },
			craft = { item = "Black Mageweave Headband", count = 3 },
			reagents = { { item = "Bolt of Mageweave", qty = 3 }, { item = "Heavy Silken Thread", qty = 2 } },
			source = "Trainer",
			alternatives = { "Bolt of Runecloth", "Black Mageweave Gloves", "Red Mageweave Vest", "Red Mageweave Pants", "Black Mageweave Shoulders", "Red Mageweave Gloves" },
		},
		{
			type = "USE",
			title = "Craft 7x Red Mageweave Bag",
			note = "Takes you from 260 to 265.",
			skill = { profession = "Tailoring", from = 260, to = 265 },
			craft = { item = "Red Mageweave Bag", count = 7 },
			reagents = { { item = "Bolt of Mageweave", qty = 4 }, { item = "Red Dye", qty = 2 }, { item = "Heavy Silken Thread", qty = 2 } },
			source = "Trainer",
			alternatives = { "Black Mageweave Headband", "Black Mageweave Shoulders", "Red Mageweave Gloves", "Mageweave Bag", "Black Mageweave Boots", "Stormcloth Gloves" },
		},
		{
			type = "USE",
			title = "Craft 7x Red Mageweave Headband",
			note = "Takes you from 265 to 270.",
			skill = { profession = "Tailoring", from = 265, to = 270 },
			craft = { item = "Red Mageweave Headband", count = 7 },
			reagents = { { item = "Bolt of Mageweave", qty = 4 }, { item = "Red Dye", qty = 2 }, { item = "Heavy Silken Thread", qty = 2 } },
			source = "Recipe: Pattern: Red Mageweave Headband",
			alternatives = { "Black Mageweave Headband", "Black Mageweave Shoulders", "Red Mageweave Gloves", "Mageweave Bag", "Black Mageweave Boots", "Red Mageweave Bag" },
		},
		{
			type = "USE",
			title = "Craft 5x Pillager's Grips",
			note = "Takes you from 270 to 280.",
			skill = { profession = "Tailoring", from = 270, to = 280 },
			craft = { item = "Pillager's Grips", count = 5 },
			reagents = { { item = "Bolt of Runecloth", qty = 2 }, { item = "Heart of Fire", qty = 4 }, { item = "Rune Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Black Mageweave Headband", "Black Mageweave Shoulders", "Black Mageweave Boots", "Red Mageweave Bag", "Red Mageweave Headband", "Red Mageweave Shoulders" },
		},
		{
			type = "USE",
			title = "Craft 7x Runecloth Belt",
			note = "Takes you from 280 to 285.",
			skill = { profession = "Tailoring", from = 280, to = 285 },
			craft = { item = "Runecloth Belt", count = 7 },
			reagents = { { item = "Bolt of Runecloth", qty = 3 }, { item = "Rune Thread", qty = 1 } },
			source = "Trainer",
			alternatives = { "Red Mageweave Headband", "Pillager's Grips", "Stormcloth Headband", "Frostweave Gloves", "Tuxedo Jacket", "Admiral's Hat" },
		},
		{
			type = "USE",
			title = "Craft 13x Frostweave Gloves",
			note = "Takes you from 285 to 295.",
			skill = { profession = "Tailoring", from = 285, to = 295 },
			craft = { item = "Frostweave Gloves", count = 13 },
			reagents = { { item = "Bolt of Runecloth", qty = 3 }, { item = "Essence of Water", qty = 1 }, { item = "Rune Thread", qty = 1 } },
			source = "Recipe: Pattern: Frostweave Gloves",
			alternatives = { "Runecloth Belt", "Tuxedo Jacket", "Cindercloth Boots", "Festival Dress", "Festival Suit", "Stormcloth Shoulders" },
		},
		{
			type = "USE",
			title = "Craft 7x Brightcloth Cloak",
			note = "Takes you from 295 to 300.",
			skill = { profession = "Tailoring", from = 295, to = 300 },
			craft = { item = "Brightcloth Cloak", count = 7 },
			reagents = { { item = "Bolt of Runecloth", qty = 4 }, { item = "Gold Bar", qty = 2 }, { item = "Rune Thread", qty = 1 } },
			source = "Recipe: Pattern: Brightcloth Cloak",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Tailoring is maxed at 300.",
		},
	},
})
